// Code generated by protoc-gen-go. DO NOT EDIT.
// source: audit.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Audit struct {
	// @inject_tag: bson:"_id"
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty" bson:"_id"`
	// @inject_tag: bson:"username"
	Username string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty" bson:"username"`
	// @inject_tag: bson:"action"
	Action string `protobuf:"bytes,3,opt,name=Action,proto3" json:"Action,omitempty" bson:"action"`
	// @inject_tag: bson:"createdby"
	CreatedBy string `protobuf:"bytes,4,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty" bson:"createdby"`
	// @inject_tag: bson:"createdat"
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty" bson:"createdat"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Audit) Reset()         { *m = Audit{} }
func (m *Audit) String() string { return proto.CompactTextString(m) }
func (*Audit) ProtoMessage()    {}
func (*Audit) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{0}
}

func (m *Audit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Audit.Unmarshal(m, b)
}
func (m *Audit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Audit.Marshal(b, m, deterministic)
}
func (m *Audit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Audit.Merge(m, src)
}
func (m *Audit) XXX_Size() int {
	return xxx_messageInfo_Audit.Size(m)
}
func (m *Audit) XXX_DiscardUnknown() {
	xxx_messageInfo_Audit.DiscardUnknown(m)
}

var xxx_messageInfo_Audit proto.InternalMessageInfo

func (m *Audit) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Audit) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Audit) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Audit) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Audit) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type AuditListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuditListReq) Reset()         { *m = AuditListReq{} }
func (m *AuditListReq) String() string { return proto.CompactTextString(m) }
func (*AuditListReq) ProtoMessage()    {}
func (*AuditListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{1}
}

func (m *AuditListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditListReq.Unmarshal(m, b)
}
func (m *AuditListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditListReq.Marshal(b, m, deterministic)
}
func (m *AuditListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditListReq.Merge(m, src)
}
func (m *AuditListReq) XXX_Size() int {
	return xxx_messageInfo_AuditListReq.Size(m)
}
func (m *AuditListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditListReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuditListReq proto.InternalMessageInfo

type AuditListRes struct {
	// return a collection of Audits
	Audits               []*Audit `protobuf:"bytes,1,rep,name=Audits,proto3" json:"Audits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuditListRes) Reset()         { *m = AuditListRes{} }
func (m *AuditListRes) String() string { return proto.CompactTextString(m) }
func (*AuditListRes) ProtoMessage()    {}
func (*AuditListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{2}
}

func (m *AuditListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditListRes.Unmarshal(m, b)
}
func (m *AuditListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditListRes.Marshal(b, m, deterministic)
}
func (m *AuditListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditListRes.Merge(m, src)
}
func (m *AuditListRes) XXX_Size() int {
	return xxx_messageInfo_AuditListRes.Size(m)
}
func (m *AuditListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditListRes.DiscardUnknown(m)
}

var xxx_messageInfo_AuditListRes proto.InternalMessageInfo

func (m *AuditListRes) GetAudits() []*Audit {
	if m != nil {
		return m.Audits
	}
	return nil
}

type AuditList100Req struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuditList100Req) Reset()         { *m = AuditList100Req{} }
func (m *AuditList100Req) String() string { return proto.CompactTextString(m) }
func (*AuditList100Req) ProtoMessage()    {}
func (*AuditList100Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{3}
}

func (m *AuditList100Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditList100Req.Unmarshal(m, b)
}
func (m *AuditList100Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditList100Req.Marshal(b, m, deterministic)
}
func (m *AuditList100Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditList100Req.Merge(m, src)
}
func (m *AuditList100Req) XXX_Size() int {
	return xxx_messageInfo_AuditList100Req.Size(m)
}
func (m *AuditList100Req) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditList100Req.DiscardUnknown(m)
}

var xxx_messageInfo_AuditList100Req proto.InternalMessageInfo

type AuditList100Res struct {
	// return a collection of Audits
	Audits               []*Audit `protobuf:"bytes,1,rep,name=Audits,proto3" json:"Audits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuditList100Res) Reset()         { *m = AuditList100Res{} }
func (m *AuditList100Res) String() string { return proto.CompactTextString(m) }
func (*AuditList100Res) ProtoMessage()    {}
func (*AuditList100Res) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{4}
}

func (m *AuditList100Res) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditList100Res.Unmarshal(m, b)
}
func (m *AuditList100Res) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditList100Res.Marshal(b, m, deterministic)
}
func (m *AuditList100Res) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditList100Res.Merge(m, src)
}
func (m *AuditList100Res) XXX_Size() int {
	return xxx_messageInfo_AuditList100Res.Size(m)
}
func (m *AuditList100Res) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditList100Res.DiscardUnknown(m)
}

var xxx_messageInfo_AuditList100Res proto.InternalMessageInfo

func (m *AuditList100Res) GetAudits() []*Audit {
	if m != nil {
		return m.Audits
	}
	return nil
}

type AuditCreateReq struct {
	// create a Audit
	Audit                *Audit   `protobuf:"bytes,1,opt,name=Audit,proto3" json:"Audit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuditCreateReq) Reset()         { *m = AuditCreateReq{} }
func (m *AuditCreateReq) String() string { return proto.CompactTextString(m) }
func (*AuditCreateReq) ProtoMessage()    {}
func (*AuditCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{5}
}

func (m *AuditCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditCreateReq.Unmarshal(m, b)
}
func (m *AuditCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditCreateReq.Marshal(b, m, deterministic)
}
func (m *AuditCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditCreateReq.Merge(m, src)
}
func (m *AuditCreateReq) XXX_Size() int {
	return xxx_messageInfo_AuditCreateReq.Size(m)
}
func (m *AuditCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuditCreateReq proto.InternalMessageInfo

func (m *AuditCreateReq) GetAudit() *Audit {
	if m != nil {
		return m.Audit
	}
	return nil
}

type AuditCreateRes struct {
	// reutrn an id
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuditCreateRes) Reset()         { *m = AuditCreateRes{} }
func (m *AuditCreateRes) String() string { return proto.CompactTextString(m) }
func (*AuditCreateRes) ProtoMessage()    {}
func (*AuditCreateRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{6}
}

func (m *AuditCreateRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditCreateRes.Unmarshal(m, b)
}
func (m *AuditCreateRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditCreateRes.Marshal(b, m, deterministic)
}
func (m *AuditCreateRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditCreateRes.Merge(m, src)
}
func (m *AuditCreateRes) XXX_Size() int {
	return xxx_messageInfo_AuditCreateRes.Size(m)
}
func (m *AuditCreateRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditCreateRes.DiscardUnknown(m)
}

var xxx_messageInfo_AuditCreateRes proto.InternalMessageInfo

func (m *AuditCreateRes) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type AuditReadReq struct {
	// read a Audit by id
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuditReadReq) Reset()         { *m = AuditReadReq{} }
func (m *AuditReadReq) String() string { return proto.CompactTextString(m) }
func (*AuditReadReq) ProtoMessage()    {}
func (*AuditReadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{7}
}

func (m *AuditReadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditReadReq.Unmarshal(m, b)
}
func (m *AuditReadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditReadReq.Marshal(b, m, deterministic)
}
func (m *AuditReadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditReadReq.Merge(m, src)
}
func (m *AuditReadReq) XXX_Size() int {
	return xxx_messageInfo_AuditReadReq.Size(m)
}
func (m *AuditReadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditReadReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuditReadReq proto.InternalMessageInfo

func (m *AuditReadReq) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type AuditReadRes struct {
	// return a Audit
	Audit                *Audit   `protobuf:"bytes,1,opt,name=Audit,proto3" json:"Audit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuditReadRes) Reset()         { *m = AuditReadRes{} }
func (m *AuditReadRes) String() string { return proto.CompactTextString(m) }
func (*AuditReadRes) ProtoMessage()    {}
func (*AuditReadRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_5594839dd8e38a1b, []int{8}
}

func (m *AuditReadRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditReadRes.Unmarshal(m, b)
}
func (m *AuditReadRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditReadRes.Marshal(b, m, deterministic)
}
func (m *AuditReadRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditReadRes.Merge(m, src)
}
func (m *AuditReadRes) XXX_Size() int {
	return xxx_messageInfo_AuditReadRes.Size(m)
}
func (m *AuditReadRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditReadRes.DiscardUnknown(m)
}

var xxx_messageInfo_AuditReadRes proto.InternalMessageInfo

func (m *AuditReadRes) GetAudit() *Audit {
	if m != nil {
		return m.Audit
	}
	return nil
}

func init() {
	proto.RegisterType((*Audit)(nil), "api.Audit")
	proto.RegisterType((*AuditListReq)(nil), "api.AuditListReq")
	proto.RegisterType((*AuditListRes)(nil), "api.AuditListRes")
	proto.RegisterType((*AuditList100Req)(nil), "api.AuditList100Req")
	proto.RegisterType((*AuditList100Res)(nil), "api.AuditList100Res")
	proto.RegisterType((*AuditCreateReq)(nil), "api.AuditCreateReq")
	proto.RegisterType((*AuditCreateRes)(nil), "api.AuditCreateRes")
	proto.RegisterType((*AuditReadReq)(nil), "api.AuditReadReq")
	proto.RegisterType((*AuditReadRes)(nil), "api.AuditReadRes")
}

func init() { proto.RegisterFile("audit.proto", fileDescriptor_5594839dd8e38a1b) }

var fileDescriptor_5594839dd8e38a1b = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0xff, 0x44, 0x3b, 0x95, 0x4a, 0x47, 0x91, 0xb0, 0x88, 0x86, 0x3d, 0xf5, 0x20,
	0x69, 0x8d, 0x14, 0xbc, 0x56, 0x7b, 0x29, 0x78, 0x8a, 0xfa, 0x00, 0xdb, 0x76, 0x2d, 0x0b, 0xa6,
	0x49, 0xb3, 0x5b, 0xc1, 0xe7, 0xf1, 0x99, 0x7c, 0x1f, 0xc9, 0xee, 0x36, 0x31, 0x69, 0x41, 0x6f,
	0x99, 0xef, 0x37, 0x33, 0xf9, 0xe6, 0x63, 0xa1, 0xcb, 0xb6, 0x4b, 0xa1, 0x82, 0x34, 0x4b, 0x54,
	0x82, 0x4d, 0x96, 0x0a, 0x72, 0xbd, 0x4a, 0x92, 0xd5, 0x3b, 0x1f, 0x6a, 0x69, 0xbe, 0x7d, 0x1b,
	0x2a, 0x11, 0x73, 0xa9, 0x58, 0x9c, 0x9a, 0x2e, 0xfa, 0xe5, 0x40, 0x7b, 0x92, 0x4f, 0x61, 0x0f,
	0x1a, 0xb3, 0xa9, 0xe7, 0xf8, 0xce, 0xa0, 0x13, 0x35, 0x66, 0x53, 0x24, 0x70, 0xfc, 0x2a, 0x79,
	0xb6, 0x66, 0x31, 0xf7, 0x1a, 0x5a, 0x2d, 0x6a, 0xbc, 0x00, 0x77, 0xb2, 0x50, 0x22, 0x59, 0x7b,
	0x4d, 0x4d, 0x6c, 0x85, 0x97, 0xd0, 0x79, 0xcc, 0x38, 0x53, 0x7c, 0xf9, 0xf0, 0xe9, 0xb5, 0x34,
	0x2a, 0x05, 0xbc, 0x2f, 0xe8, 0x44, 0x79, 0x6d, 0xdf, 0x19, 0x74, 0x43, 0x12, 0x18, 0x83, 0xc1,
	0xce, 0x60, 0xf0, 0xb2, 0x33, 0x18, 0x95, 0xcd, 0xb4, 0x07, 0x27, 0xda, 0xe4, 0x93, 0x90, 0x2a,
	0xe2, 0x1b, 0x1a, 0x56, 0x6a, 0x89, 0x14, 0x5c, 0x5d, 0x4b, 0xcf, 0xf1, 0x9b, 0x83, 0x6e, 0x08,
	0x01, 0x4b, 0x45, 0xa0, 0xa5, 0xc8, 0x12, 0xda, 0x87, 0xd3, 0x62, 0xe6, 0x76, 0x34, 0xca, 0xd7,
	0x8c, 0xeb, 0xd2, 0xff, 0x36, 0x85, 0xd0, 0xd3, 0x5f, 0xc6, 0x5f, 0xc4, 0x37, 0xe8, 0xdb, 0x10,
	0x75, 0x7c, 0xd5, 0x21, 0x03, 0xa8, 0x5f, 0x9b, 0x91, 0xf5, 0xbc, 0xe9, 0x95, 0xbd, 0x29, 0xe2,
	0x6c, 0x99, 0xef, 0xac, 0xf3, 0x51, 0x85, 0xcb, 0xbf, 0xff, 0x19, 0x7e, 0x3b, 0x76, 0xe4, 0x99,
	0x67, 0x1f, 0x62, 0xc1, 0xf1, 0x06, 0x5a, 0xf9, 0xa9, 0xd8, 0x2f, 0x7b, 0x6d, 0xa2, 0x64, 0x4f,
	0x92, 0x38, 0x86, 0x23, 0x1b, 0x0c, 0x9e, 0x57, 0xa9, 0x89, 0x8f, 0x1c, 0x52, 0x25, 0x86, 0xe0,
	0x9a, 0x23, 0xf1, 0xac, 0xe4, 0x45, 0x54, 0xe4, 0x80, 0x28, 0x73, 0x63, 0xf9, 0x59, 0xbf, 0x8d,
	0xd9, 0x18, 0xc8, 0x9e, 0x24, 0xe7, 0xae, 0x7e, 0x2c, 0x77, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x67, 0x68, 0x17, 0xeb, 0xef, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuditServiceClient is the client API for AuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuditServiceClient interface {
	List(ctx context.Context, in *AuditListReq, opts ...grpc.CallOption) (*AuditListRes, error)
	List100(ctx context.Context, in *AuditList100Req, opts ...grpc.CallOption) (*AuditList100Res, error)
	Create(ctx context.Context, in *AuditCreateReq, opts ...grpc.CallOption) (*AuditCreateRes, error)
	Read(ctx context.Context, in *AuditReadReq, opts ...grpc.CallOption) (*AuditReadRes, error)
}

type auditServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuditServiceClient(cc *grpc.ClientConn) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) List(ctx context.Context, in *AuditListReq, opts ...grpc.CallOption) (*AuditListRes, error) {
	out := new(AuditListRes)
	err := c.cc.Invoke(ctx, "/api.AuditService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) List100(ctx context.Context, in *AuditList100Req, opts ...grpc.CallOption) (*AuditList100Res, error) {
	out := new(AuditList100Res)
	err := c.cc.Invoke(ctx, "/api.AuditService/List100", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) Create(ctx context.Context, in *AuditCreateReq, opts ...grpc.CallOption) (*AuditCreateRes, error) {
	out := new(AuditCreateRes)
	err := c.cc.Invoke(ctx, "/api.AuditService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) Read(ctx context.Context, in *AuditReadReq, opts ...grpc.CallOption) (*AuditReadRes, error) {
	out := new(AuditReadRes)
	err := c.cc.Invoke(ctx, "/api.AuditService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditServiceServer is the server API for AuditService service.
type AuditServiceServer interface {
	List(context.Context, *AuditListReq) (*AuditListRes, error)
	List100(context.Context, *AuditList100Req) (*AuditList100Res, error)
	Create(context.Context, *AuditCreateReq) (*AuditCreateRes, error)
	Read(context.Context, *AuditReadReq) (*AuditReadRes, error)
}

func RegisterAuditServiceServer(s *grpc.Server, srv AuditServiceServer) {
	s.RegisterService(&_AuditService_serviceDesc, srv)
}

func _AuditService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AuditService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).List(ctx, req.(*AuditListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_List100_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditList100Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).List100(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AuditService/List100",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).List100(ctx, req.(*AuditList100Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AuditService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).Create(ctx, req.(*AuditCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AuditService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).Read(ctx, req.(*AuditReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuditService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AuditService_List_Handler,
		},
		{
			MethodName: "List100",
			Handler:    _AuditService_List100_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AuditService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _AuditService_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audit.proto",
}
