// Code generated by protoc-gen-go. DO NOT EDIT.
// source: role.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Role struct {
	ID                   string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	CreatedBy            string               `protobuf:"bytes,4,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	ModifiedBy           string               `protobuf:"bytes,6,opt,name=ModifiedBy,proto3" json:"ModifiedBy,omitempty"`
	ModifiedAt           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=ModifiedAt,proto3" json:"ModifiedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{0}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Role) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Role) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Role) GetModifiedBy() string {
	if m != nil {
		return m.ModifiedBy
	}
	return ""
}

func (m *Role) GetModifiedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedAt
	}
	return nil
}

type RoleSliceReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleSliceReq) Reset()         { *m = RoleSliceReq{} }
func (m *RoleSliceReq) String() string { return proto.CompactTextString(m) }
func (*RoleSliceReq) ProtoMessage()    {}
func (*RoleSliceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{1}
}

func (m *RoleSliceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleSliceReq.Unmarshal(m, b)
}
func (m *RoleSliceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleSliceReq.Marshal(b, m, deterministic)
}
func (m *RoleSliceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleSliceReq.Merge(m, src)
}
func (m *RoleSliceReq) XXX_Size() int {
	return xxx_messageInfo_RoleSliceReq.Size(m)
}
func (m *RoleSliceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleSliceReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoleSliceReq proto.InternalMessageInfo

type RoleSliceRes struct {
	// return a collection of Roles
	Roles                []*Role  `protobuf:"bytes,1,rep,name=Roles,proto3" json:"Roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleSliceRes) Reset()         { *m = RoleSliceRes{} }
func (m *RoleSliceRes) String() string { return proto.CompactTextString(m) }
func (*RoleSliceRes) ProtoMessage()    {}
func (*RoleSliceRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{2}
}

func (m *RoleSliceRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleSliceRes.Unmarshal(m, b)
}
func (m *RoleSliceRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleSliceRes.Marshal(b, m, deterministic)
}
func (m *RoleSliceRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleSliceRes.Merge(m, src)
}
func (m *RoleSliceRes) XXX_Size() int {
	return xxx_messageInfo_RoleSliceRes.Size(m)
}
func (m *RoleSliceRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleSliceRes.DiscardUnknown(m)
}

var xxx_messageInfo_RoleSliceRes proto.InternalMessageInfo

func (m *RoleSliceRes) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type RoleCreateReq struct {
	// create a Role
	Role                 *Role    `protobuf:"bytes,1,opt,name=Role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleCreateReq) Reset()         { *m = RoleCreateReq{} }
func (m *RoleCreateReq) String() string { return proto.CompactTextString(m) }
func (*RoleCreateReq) ProtoMessage()    {}
func (*RoleCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{3}
}

func (m *RoleCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleCreateReq.Unmarshal(m, b)
}
func (m *RoleCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleCreateReq.Marshal(b, m, deterministic)
}
func (m *RoleCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleCreateReq.Merge(m, src)
}
func (m *RoleCreateReq) XXX_Size() int {
	return xxx_messageInfo_RoleCreateReq.Size(m)
}
func (m *RoleCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoleCreateReq proto.InternalMessageInfo

func (m *RoleCreateReq) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type RoleCreateRes struct {
	// reutrn an id
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleCreateRes) Reset()         { *m = RoleCreateRes{} }
func (m *RoleCreateRes) String() string { return proto.CompactTextString(m) }
func (*RoleCreateRes) ProtoMessage()    {}
func (*RoleCreateRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{4}
}

func (m *RoleCreateRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleCreateRes.Unmarshal(m, b)
}
func (m *RoleCreateRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleCreateRes.Marshal(b, m, deterministic)
}
func (m *RoleCreateRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleCreateRes.Merge(m, src)
}
func (m *RoleCreateRes) XXX_Size() int {
	return xxx_messageInfo_RoleCreateRes.Size(m)
}
func (m *RoleCreateRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleCreateRes.DiscardUnknown(m)
}

var xxx_messageInfo_RoleCreateRes proto.InternalMessageInfo

func (m *RoleCreateRes) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RoleReadReq struct {
	// read a Role by id
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleReadReq) Reset()         { *m = RoleReadReq{} }
func (m *RoleReadReq) String() string { return proto.CompactTextString(m) }
func (*RoleReadReq) ProtoMessage()    {}
func (*RoleReadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{5}
}

func (m *RoleReadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleReadReq.Unmarshal(m, b)
}
func (m *RoleReadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleReadReq.Marshal(b, m, deterministic)
}
func (m *RoleReadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleReadReq.Merge(m, src)
}
func (m *RoleReadReq) XXX_Size() int {
	return xxx_messageInfo_RoleReadReq.Size(m)
}
func (m *RoleReadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleReadReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoleReadReq proto.InternalMessageInfo

func (m *RoleReadReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RoleReadRes struct {
	// return a Role
	Role                 *Role    `protobuf:"bytes,1,opt,name=Role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleReadRes) Reset()         { *m = RoleReadRes{} }
func (m *RoleReadRes) String() string { return proto.CompactTextString(m) }
func (*RoleReadRes) ProtoMessage()    {}
func (*RoleReadRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{6}
}

func (m *RoleReadRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleReadRes.Unmarshal(m, b)
}
func (m *RoleReadRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleReadRes.Marshal(b, m, deterministic)
}
func (m *RoleReadRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleReadRes.Merge(m, src)
}
func (m *RoleReadRes) XXX_Size() int {
	return xxx_messageInfo_RoleReadRes.Size(m)
}
func (m *RoleReadRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleReadRes.DiscardUnknown(m)
}

var xxx_messageInfo_RoleReadRes proto.InternalMessageInfo

func (m *RoleReadRes) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type RoleUpdateReq struct {
	// update a Role by id
	Role                 *Role    `protobuf:"bytes,1,opt,name=Role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleUpdateReq) Reset()         { *m = RoleUpdateReq{} }
func (m *RoleUpdateReq) String() string { return proto.CompactTextString(m) }
func (*RoleUpdateReq) ProtoMessage()    {}
func (*RoleUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{7}
}

func (m *RoleUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleUpdateReq.Unmarshal(m, b)
}
func (m *RoleUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleUpdateReq.Marshal(b, m, deterministic)
}
func (m *RoleUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleUpdateReq.Merge(m, src)
}
func (m *RoleUpdateReq) XXX_Size() int {
	return xxx_messageInfo_RoleUpdateReq.Size(m)
}
func (m *RoleUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoleUpdateReq proto.InternalMessageInfo

func (m *RoleUpdateReq) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type RoleUpdateRes struct {
	// return number of Roles updated
	// should equal 1 on success
	Updated              int64    `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleUpdateRes) Reset()         { *m = RoleUpdateRes{} }
func (m *RoleUpdateRes) String() string { return proto.CompactTextString(m) }
func (*RoleUpdateRes) ProtoMessage()    {}
func (*RoleUpdateRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{8}
}

func (m *RoleUpdateRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleUpdateRes.Unmarshal(m, b)
}
func (m *RoleUpdateRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleUpdateRes.Marshal(b, m, deterministic)
}
func (m *RoleUpdateRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleUpdateRes.Merge(m, src)
}
func (m *RoleUpdateRes) XXX_Size() int {
	return xxx_messageInfo_RoleUpdateRes.Size(m)
}
func (m *RoleUpdateRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleUpdateRes.DiscardUnknown(m)
}

var xxx_messageInfo_RoleUpdateRes proto.InternalMessageInfo

func (m *RoleUpdateRes) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type RoleDeleteReq struct {
	// delete a Role by id
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleDeleteReq) Reset()         { *m = RoleDeleteReq{} }
func (m *RoleDeleteReq) String() string { return proto.CompactTextString(m) }
func (*RoleDeleteReq) ProtoMessage()    {}
func (*RoleDeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{9}
}

func (m *RoleDeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleDeleteReq.Unmarshal(m, b)
}
func (m *RoleDeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleDeleteReq.Marshal(b, m, deterministic)
}
func (m *RoleDeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleDeleteReq.Merge(m, src)
}
func (m *RoleDeleteReq) XXX_Size() int {
	return xxx_messageInfo_RoleDeleteReq.Size(m)
}
func (m *RoleDeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleDeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoleDeleteReq proto.InternalMessageInfo

func (m *RoleDeleteReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RoleDeleteRes struct {
	// return number of Roles deleted
	// should equal 1 on success
	Deleted              int64    `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleDeleteRes) Reset()         { *m = RoleDeleteRes{} }
func (m *RoleDeleteRes) String() string { return proto.CompactTextString(m) }
func (*RoleDeleteRes) ProtoMessage()    {}
func (*RoleDeleteRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a3ff9f7c9032f8, []int{10}
}

func (m *RoleDeleteRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleDeleteRes.Unmarshal(m, b)
}
func (m *RoleDeleteRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleDeleteRes.Marshal(b, m, deterministic)
}
func (m *RoleDeleteRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleDeleteRes.Merge(m, src)
}
func (m *RoleDeleteRes) XXX_Size() int {
	return xxx_messageInfo_RoleDeleteRes.Size(m)
}
func (m *RoleDeleteRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleDeleteRes.DiscardUnknown(m)
}

var xxx_messageInfo_RoleDeleteRes proto.InternalMessageInfo

func (m *RoleDeleteRes) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

func init() {
	proto.RegisterType((*Role)(nil), "api.Role")
	proto.RegisterType((*RoleSliceReq)(nil), "api.RoleSliceReq")
	proto.RegisterType((*RoleSliceRes)(nil), "api.RoleSliceRes")
	proto.RegisterType((*RoleCreateReq)(nil), "api.RoleCreateReq")
	proto.RegisterType((*RoleCreateRes)(nil), "api.RoleCreateRes")
	proto.RegisterType((*RoleReadReq)(nil), "api.RoleReadReq")
	proto.RegisterType((*RoleReadRes)(nil), "api.RoleReadRes")
	proto.RegisterType((*RoleUpdateReq)(nil), "api.RoleUpdateReq")
	proto.RegisterType((*RoleUpdateRes)(nil), "api.RoleUpdateRes")
	proto.RegisterType((*RoleDeleteReq)(nil), "api.RoleDeleteReq")
	proto.RegisterType((*RoleDeleteRes)(nil), "api.RoleDeleteRes")
}

func init() { proto.RegisterFile("role.proto", fileDescriptor_48a3ff9f7c9032f8) }

var fileDescriptor_48a3ff9f7c9032f8 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x3d, 0xaf, 0xd3, 0x40,
	0x10, 0x94, 0x3f, 0x92, 0xa7, 0xac, 0xe1, 0x09, 0xb6, 0x3a, 0x59, 0x3c, 0x62, 0xb9, 0xca, 0x43,
	0xe0, 0xa0, 0xd0, 0x20, 0xba, 0x07, 0x6e, 0x52, 0x40, 0xe1, 0xc0, 0x0f, 0x70, 0xe2, 0x4d, 0x74,
	0x92, 0xc3, 0x39, 0x3e, 0x07, 0x89, 0x8e, 0x5f, 0x8e, 0x90, 0xf7, 0xe2, 0xaf, 0xb8, 0x08, 0xdd,
	0xed, 0xcc, 0xdc, 0x78, 0x6e, 0xd6, 0x00, 0xa5, 0xca, 0x29, 0x2a, 0x4a, 0x55, 0x29, 0x74, 0xd2,
	0x42, 0xfa, 0xf3, 0x83, 0x52, 0x87, 0x9c, 0x96, 0x0c, 0x6d, 0xcf, 0xfb, 0x65, 0x25, 0x8f, 0xa4,
	0xab, 0xf4, 0x58, 0x18, 0x55, 0xf8, 0xc7, 0x06, 0x37, 0x51, 0x39, 0xe1, 0x3d, 0xd8, 0xeb, 0x58,
	0x58, 0x81, 0xb5, 0x98, 0x25, 0xf6, 0x3a, 0x46, 0x04, 0xf7, 0x5b, 0x7a, 0x24, 0x61, 0x33, 0xc2,
	0x67, 0x0c, 0xc0, 0x8b, 0x49, 0xef, 0x4a, 0x59, 0x54, 0x52, 0xfd, 0x14, 0x0e, 0x53, 0x7d, 0x08,
	0x5f, 0xc1, 0xec, 0x4b, 0x49, 0x69, 0x45, 0xd9, 0xe7, 0xdf, 0xc2, 0x65, 0xbe, 0x03, 0xf0, 0x63,
	0xcb, 0x3e, 0x55, 0x62, 0x12, 0x58, 0x0b, 0x6f, 0xe5, 0x47, 0x26, 0x61, 0xd4, 0x24, 0x8c, 0xbe,
	0x37, 0x09, 0x93, 0x4e, 0x8c, 0xaf, 0x01, 0xbe, 0xaa, 0x4c, 0xee, 0x25, 0x1b, 0x4f, 0xd9, 0xb8,
	0x87, 0xe0, 0xa7, 0x8e, 0x7f, 0xaa, 0xc4, 0xdd, 0x4d, 0xeb, 0x9e, 0x3a, 0xbc, 0x87, 0x67, 0x75,
	0x03, 0x9b, 0x5c, 0xee, 0x28, 0xa1, 0x53, 0xb8, 0x1c, 0xcc, 0x1a, 0xe7, 0x30, 0xa9, 0x67, 0x2d,
	0xac, 0xc0, 0x59, 0x78, 0xab, 0x59, 0x94, 0x16, 0x32, 0xaa, 0x91, 0xc4, 0xe0, 0x61, 0x04, 0xcf,
	0xeb, 0x83, 0x49, 0x9b, 0xd0, 0x09, 0x1f, 0x4c, 0xa7, 0xdc, 0xe6, 0xe0, 0x02, 0xc3, 0xe1, 0x7c,
	0xa8, 0xd7, 0x75, 0xf7, 0x32, 0x6b, 0xba, 0x97, 0x59, 0xf8, 0x00, 0x1e, 0xcb, 0x29, 0xcd, 0x6a,
	0xbb, 0x6b, 0xfa, 0x6d, 0x9f, 0xd6, 0xb7, 0xbe, 0x76, 0x49, 0xf7, 0xa3, 0xc8, 0xfe, 0x2f, 0xdd,
	0xe3, 0x50, 0xaf, 0x51, 0xc0, 0xdd, 0x99, 0x07, 0x93, 0xc1, 0x49, 0x9a, 0xb1, 0x79, 0x48, 0x4c,
	0x39, 0x19, 0xeb, 0xeb, 0xa4, 0x8f, 0x43, 0x01, 0x7b, 0x65, 0x3c, 0xb4, 0x5e, 0x97, 0x71, 0xf5,
	0xd7, 0x32, 0xaf, 0xda, 0x50, 0xf9, 0x4b, 0xee, 0x08, 0xdf, 0xc1, 0x84, 0x37, 0x80, 0x2f, 0xdb,
	0x80, 0xcd, 0x86, 0xfc, 0x11, 0xa4, 0xf1, 0x3d, 0x4c, 0x4d, 0x9f, 0x88, 0x2d, 0xd9, 0x2e, 0xc4,
	0x1f, 0x63, 0x1a, 0xdf, 0x80, 0x5b, 0x37, 0x88, 0x2f, 0xba, 0x02, 0x4c, 0xdf, 0xfe, 0x35, 0xc2,
	0xee, 0xa6, 0x8f, 0x9e, 0x7b, 0x5b, 0xa8, 0x3f, 0xc6, 0xf8, 0x86, 0x79, 0x75, 0xef, 0x46, 0xdb,
	0x93, 0x3f, 0xc6, 0xf4, 0x76, 0xca, 0xbf, 0xe9, 0x87, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8a,
	0x6c, 0x89, 0xc7, 0xc4, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoleServiceClient is the client API for RoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoleServiceClient interface {
	Slice(ctx context.Context, in *RoleSliceReq, opts ...grpc.CallOption) (*RoleSliceRes, error)
	Create(ctx context.Context, in *RoleCreateReq, opts ...grpc.CallOption) (*RoleCreateRes, error)
	Read(ctx context.Context, in *RoleReadReq, opts ...grpc.CallOption) (*RoleReadRes, error)
	Update(ctx context.Context, in *RoleUpdateReq, opts ...grpc.CallOption) (*RoleUpdateRes, error)
	Delete(ctx context.Context, in *RoleDeleteReq, opts ...grpc.CallOption) (*RoleDeleteRes, error)
}

type roleServiceClient struct {
	cc *grpc.ClientConn
}

func NewRoleServiceClient(cc *grpc.ClientConn) RoleServiceClient {
	return &roleServiceClient{cc}
}

func (c *roleServiceClient) Slice(ctx context.Context, in *RoleSliceReq, opts ...grpc.CallOption) (*RoleSliceRes, error) {
	out := new(RoleSliceRes)
	err := c.cc.Invoke(ctx, "/api.RoleService/Slice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) Create(ctx context.Context, in *RoleCreateReq, opts ...grpc.CallOption) (*RoleCreateRes, error) {
	out := new(RoleCreateRes)
	err := c.cc.Invoke(ctx, "/api.RoleService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) Read(ctx context.Context, in *RoleReadReq, opts ...grpc.CallOption) (*RoleReadRes, error) {
	out := new(RoleReadRes)
	err := c.cc.Invoke(ctx, "/api.RoleService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) Update(ctx context.Context, in *RoleUpdateReq, opts ...grpc.CallOption) (*RoleUpdateRes, error) {
	out := new(RoleUpdateRes)
	err := c.cc.Invoke(ctx, "/api.RoleService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) Delete(ctx context.Context, in *RoleDeleteReq, opts ...grpc.CallOption) (*RoleDeleteRes, error) {
	out := new(RoleDeleteRes)
	err := c.cc.Invoke(ctx, "/api.RoleService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleServiceServer is the server API for RoleService service.
type RoleServiceServer interface {
	Slice(context.Context, *RoleSliceReq) (*RoleSliceRes, error)
	Create(context.Context, *RoleCreateReq) (*RoleCreateRes, error)
	Read(context.Context, *RoleReadReq) (*RoleReadRes, error)
	Update(context.Context, *RoleUpdateReq) (*RoleUpdateRes, error)
	Delete(context.Context, *RoleDeleteReq) (*RoleDeleteRes, error)
}

func RegisterRoleServiceServer(s *grpc.Server, srv RoleServiceServer) {
	s.RegisterService(&_RoleService_serviceDesc, srv)
}

func _RoleService_Slice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleSliceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).Slice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RoleService/Slice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).Slice(ctx, req.(*RoleSliceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RoleService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).Create(ctx, req.(*RoleCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RoleService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).Read(ctx, req.(*RoleReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RoleService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).Update(ctx, req.(*RoleUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RoleService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).Delete(ctx, req.(*RoleDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.RoleService",
	HandlerType: (*RoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Slice",
			Handler:    _RoleService_Slice_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _RoleService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _RoleService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _RoleService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RoleService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "role.proto",
}
