// Code generated by protoc-gen-go. DO NOT EDIT.
// source: route.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Route struct {
	// @inject_tag: bson:"_id"
	ID *wrappers.StringValue `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty" bson:"_id"`
	// @inject_tag: bson:"roleid"
	RoleID *wrappers.StringValue `protobuf:"bytes,2,opt,name=RoleID,proto3" json:"RoleID,omitempty" bson:"roleid"`
	// @inject_tag: bson:"path"
	Path *wrappers.StringValue `protobuf:"bytes,3,opt,name=Path,proto3" json:"Path,omitempty" bson:"path"`
	// @inject_tag: bson:"permission"
	Permission *wrappers.BoolValue `protobuf:"bytes,4,opt,name=Permission,proto3" json:"Permission,omitempty" bson:"permission"`
	// @inject_tag: bson:"createdby"
	CreatedBy *wrappers.StringValue `protobuf:"bytes,5,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty" bson:"createdby"`
	// @inject_tag: bson:"createdat"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty" bson:"createdat"`
	// @inject_tag: bson:"modifiedby"
	ModifiedBy *wrappers.StringValue `protobuf:"bytes,7,opt,name=ModifiedBy,proto3" json:"ModifiedBy,omitempty" bson:"modifiedby"`
	// @inject_tag: bson:"modifiedat"
	ModifiedAt           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=ModifiedAt,proto3" json:"ModifiedAt,omitempty" bson:"modifiedat"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{0}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetID() *wrappers.StringValue {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *Route) GetRoleID() *wrappers.StringValue {
	if m != nil {
		return m.RoleID
	}
	return nil
}

func (m *Route) GetPath() *wrappers.StringValue {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *Route) GetPermission() *wrappers.BoolValue {
	if m != nil {
		return m.Permission
	}
	return nil
}

func (m *Route) GetCreatedBy() *wrappers.StringValue {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *Route) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Route) GetModifiedBy() *wrappers.StringValue {
	if m != nil {
		return m.ModifiedBy
	}
	return nil
}

func (m *Route) GetModifiedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedAt
	}
	return nil
}

type RouteListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteListReq) Reset()         { *m = RouteListReq{} }
func (m *RouteListReq) String() string { return proto.CompactTextString(m) }
func (*RouteListReq) ProtoMessage()    {}
func (*RouteListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{1}
}

func (m *RouteListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteListReq.Unmarshal(m, b)
}
func (m *RouteListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteListReq.Marshal(b, m, deterministic)
}
func (m *RouteListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteListReq.Merge(m, src)
}
func (m *RouteListReq) XXX_Size() int {
	return xxx_messageInfo_RouteListReq.Size(m)
}
func (m *RouteListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteListReq.DiscardUnknown(m)
}

var xxx_messageInfo_RouteListReq proto.InternalMessageInfo

type RouteListRes struct {
	// return a collection of Routes
	Routes               []*Route `protobuf:"bytes,1,rep,name=Routes,proto3" json:"Routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteListRes) Reset()         { *m = RouteListRes{} }
func (m *RouteListRes) String() string { return proto.CompactTextString(m) }
func (*RouteListRes) ProtoMessage()    {}
func (*RouteListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{2}
}

func (m *RouteListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteListRes.Unmarshal(m, b)
}
func (m *RouteListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteListRes.Marshal(b, m, deterministic)
}
func (m *RouteListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteListRes.Merge(m, src)
}
func (m *RouteListRes) XXX_Size() int {
	return xxx_messageInfo_RouteListRes.Size(m)
}
func (m *RouteListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteListRes.DiscardUnknown(m)
}

var xxx_messageInfo_RouteListRes proto.InternalMessageInfo

func (m *RouteListRes) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type RouteListByRoleIDReq struct {
	RoleID               *wrappers.StringValue `protobuf:"bytes,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RouteListByRoleIDReq) Reset()         { *m = RouteListByRoleIDReq{} }
func (m *RouteListByRoleIDReq) String() string { return proto.CompactTextString(m) }
func (*RouteListByRoleIDReq) ProtoMessage()    {}
func (*RouteListByRoleIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{3}
}

func (m *RouteListByRoleIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteListByRoleIDReq.Unmarshal(m, b)
}
func (m *RouteListByRoleIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteListByRoleIDReq.Marshal(b, m, deterministic)
}
func (m *RouteListByRoleIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteListByRoleIDReq.Merge(m, src)
}
func (m *RouteListByRoleIDReq) XXX_Size() int {
	return xxx_messageInfo_RouteListByRoleIDReq.Size(m)
}
func (m *RouteListByRoleIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteListByRoleIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_RouteListByRoleIDReq proto.InternalMessageInfo

func (m *RouteListByRoleIDReq) GetRoleID() *wrappers.StringValue {
	if m != nil {
		return m.RoleID
	}
	return nil
}

type RouteListByRoleIDRes struct {
	// return a collection of Routes
	Routes               []*Route `protobuf:"bytes,1,rep,name=Routes,proto3" json:"Routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteListByRoleIDRes) Reset()         { *m = RouteListByRoleIDRes{} }
func (m *RouteListByRoleIDRes) String() string { return proto.CompactTextString(m) }
func (*RouteListByRoleIDRes) ProtoMessage()    {}
func (*RouteListByRoleIDRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{4}
}

func (m *RouteListByRoleIDRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteListByRoleIDRes.Unmarshal(m, b)
}
func (m *RouteListByRoleIDRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteListByRoleIDRes.Marshal(b, m, deterministic)
}
func (m *RouteListByRoleIDRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteListByRoleIDRes.Merge(m, src)
}
func (m *RouteListByRoleIDRes) XXX_Size() int {
	return xxx_messageInfo_RouteListByRoleIDRes.Size(m)
}
func (m *RouteListByRoleIDRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteListByRoleIDRes.DiscardUnknown(m)
}

var xxx_messageInfo_RouteListByRoleIDRes proto.InternalMessageInfo

func (m *RouteListByRoleIDRes) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type RouteCreateReq struct {
	// create a Route
	Route                *Route   `protobuf:"bytes,1,opt,name=Route,proto3" json:"Route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteCreateReq) Reset()         { *m = RouteCreateReq{} }
func (m *RouteCreateReq) String() string { return proto.CompactTextString(m) }
func (*RouteCreateReq) ProtoMessage()    {}
func (*RouteCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{5}
}

func (m *RouteCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteCreateReq.Unmarshal(m, b)
}
func (m *RouteCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteCreateReq.Marshal(b, m, deterministic)
}
func (m *RouteCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteCreateReq.Merge(m, src)
}
func (m *RouteCreateReq) XXX_Size() int {
	return xxx_messageInfo_RouteCreateReq.Size(m)
}
func (m *RouteCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_RouteCreateReq proto.InternalMessageInfo

func (m *RouteCreateReq) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type RouteCreateRes struct {
	// reutrn an id
	ID                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RouteCreateRes) Reset()         { *m = RouteCreateRes{} }
func (m *RouteCreateRes) String() string { return proto.CompactTextString(m) }
func (*RouteCreateRes) ProtoMessage()    {}
func (*RouteCreateRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{6}
}

func (m *RouteCreateRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteCreateRes.Unmarshal(m, b)
}
func (m *RouteCreateRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteCreateRes.Marshal(b, m, deterministic)
}
func (m *RouteCreateRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteCreateRes.Merge(m, src)
}
func (m *RouteCreateRes) XXX_Size() int {
	return xxx_messageInfo_RouteCreateRes.Size(m)
}
func (m *RouteCreateRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteCreateRes.DiscardUnknown(m)
}

var xxx_messageInfo_RouteCreateRes proto.InternalMessageInfo

func (m *RouteCreateRes) GetID() *wrappers.StringValue {
	if m != nil {
		return m.ID
	}
	return nil
}

type RouteReadReq struct {
	// read a Route by id
	ID                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RouteReadReq) Reset()         { *m = RouteReadReq{} }
func (m *RouteReadReq) String() string { return proto.CompactTextString(m) }
func (*RouteReadReq) ProtoMessage()    {}
func (*RouteReadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{7}
}

func (m *RouteReadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteReadReq.Unmarshal(m, b)
}
func (m *RouteReadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteReadReq.Marshal(b, m, deterministic)
}
func (m *RouteReadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteReadReq.Merge(m, src)
}
func (m *RouteReadReq) XXX_Size() int {
	return xxx_messageInfo_RouteReadReq.Size(m)
}
func (m *RouteReadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteReadReq.DiscardUnknown(m)
}

var xxx_messageInfo_RouteReadReq proto.InternalMessageInfo

func (m *RouteReadReq) GetID() *wrappers.StringValue {
	if m != nil {
		return m.ID
	}
	return nil
}

type RouteReadRes struct {
	// return a Route
	Route                *Route   `protobuf:"bytes,1,opt,name=Route,proto3" json:"Route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteReadRes) Reset()         { *m = RouteReadRes{} }
func (m *RouteReadRes) String() string { return proto.CompactTextString(m) }
func (*RouteReadRes) ProtoMessage()    {}
func (*RouteReadRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{8}
}

func (m *RouteReadRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteReadRes.Unmarshal(m, b)
}
func (m *RouteReadRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteReadRes.Marshal(b, m, deterministic)
}
func (m *RouteReadRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteReadRes.Merge(m, src)
}
func (m *RouteReadRes) XXX_Size() int {
	return xxx_messageInfo_RouteReadRes.Size(m)
}
func (m *RouteReadRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteReadRes.DiscardUnknown(m)
}

var xxx_messageInfo_RouteReadRes proto.InternalMessageInfo

func (m *RouteReadRes) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type RouteReadByRoleIDAndPathReq struct {
	// update a Route by id
	Route                *Route   `protobuf:"bytes,1,opt,name=Route,proto3" json:"Route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteReadByRoleIDAndPathReq) Reset()         { *m = RouteReadByRoleIDAndPathReq{} }
func (m *RouteReadByRoleIDAndPathReq) String() string { return proto.CompactTextString(m) }
func (*RouteReadByRoleIDAndPathReq) ProtoMessage()    {}
func (*RouteReadByRoleIDAndPathReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{9}
}

func (m *RouteReadByRoleIDAndPathReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteReadByRoleIDAndPathReq.Unmarshal(m, b)
}
func (m *RouteReadByRoleIDAndPathReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteReadByRoleIDAndPathReq.Marshal(b, m, deterministic)
}
func (m *RouteReadByRoleIDAndPathReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteReadByRoleIDAndPathReq.Merge(m, src)
}
func (m *RouteReadByRoleIDAndPathReq) XXX_Size() int {
	return xxx_messageInfo_RouteReadByRoleIDAndPathReq.Size(m)
}
func (m *RouteReadByRoleIDAndPathReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteReadByRoleIDAndPathReq.DiscardUnknown(m)
}

var xxx_messageInfo_RouteReadByRoleIDAndPathReq proto.InternalMessageInfo

func (m *RouteReadByRoleIDAndPathReq) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type RouteReadByRoleIDAndPathRes struct {
	// return a Route
	Route                *Route   `protobuf:"bytes,1,opt,name=Route,proto3" json:"Route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteReadByRoleIDAndPathRes) Reset()         { *m = RouteReadByRoleIDAndPathRes{} }
func (m *RouteReadByRoleIDAndPathRes) String() string { return proto.CompactTextString(m) }
func (*RouteReadByRoleIDAndPathRes) ProtoMessage()    {}
func (*RouteReadByRoleIDAndPathRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{10}
}

func (m *RouteReadByRoleIDAndPathRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteReadByRoleIDAndPathRes.Unmarshal(m, b)
}
func (m *RouteReadByRoleIDAndPathRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteReadByRoleIDAndPathRes.Marshal(b, m, deterministic)
}
func (m *RouteReadByRoleIDAndPathRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteReadByRoleIDAndPathRes.Merge(m, src)
}
func (m *RouteReadByRoleIDAndPathRes) XXX_Size() int {
	return xxx_messageInfo_RouteReadByRoleIDAndPathRes.Size(m)
}
func (m *RouteReadByRoleIDAndPathRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteReadByRoleIDAndPathRes.DiscardUnknown(m)
}

var xxx_messageInfo_RouteReadByRoleIDAndPathRes proto.InternalMessageInfo

func (m *RouteReadByRoleIDAndPathRes) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type RouteUpdateReq struct {
	// update a Route by id
	Route                *Route   `protobuf:"bytes,1,opt,name=Route,proto3" json:"Route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteUpdateReq) Reset()         { *m = RouteUpdateReq{} }
func (m *RouteUpdateReq) String() string { return proto.CompactTextString(m) }
func (*RouteUpdateReq) ProtoMessage()    {}
func (*RouteUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{11}
}

func (m *RouteUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteUpdateReq.Unmarshal(m, b)
}
func (m *RouteUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteUpdateReq.Marshal(b, m, deterministic)
}
func (m *RouteUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteUpdateReq.Merge(m, src)
}
func (m *RouteUpdateReq) XXX_Size() int {
	return xxx_messageInfo_RouteUpdateReq.Size(m)
}
func (m *RouteUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_RouteUpdateReq proto.InternalMessageInfo

func (m *RouteUpdateReq) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type RouteUpdateRes struct {
	// return number of Routes updated
	// should equal 1 on success
	Updated              *wrappers.Int64Value `protobuf:"bytes,1,opt,name=Updated,proto3" json:"Updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RouteUpdateRes) Reset()         { *m = RouteUpdateRes{} }
func (m *RouteUpdateRes) String() string { return proto.CompactTextString(m) }
func (*RouteUpdateRes) ProtoMessage()    {}
func (*RouteUpdateRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{12}
}

func (m *RouteUpdateRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteUpdateRes.Unmarshal(m, b)
}
func (m *RouteUpdateRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteUpdateRes.Marshal(b, m, deterministic)
}
func (m *RouteUpdateRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteUpdateRes.Merge(m, src)
}
func (m *RouteUpdateRes) XXX_Size() int {
	return xxx_messageInfo_RouteUpdateRes.Size(m)
}
func (m *RouteUpdateRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteUpdateRes.DiscardUnknown(m)
}

var xxx_messageInfo_RouteUpdateRes proto.InternalMessageInfo

func (m *RouteUpdateRes) GetUpdated() *wrappers.Int64Value {
	if m != nil {
		return m.Updated
	}
	return nil
}

type RouteUpdateByRoleIDAndPathReq struct {
	// update a Route by roleid and path
	Route                *Route   `protobuf:"bytes,1,opt,name=Route,proto3" json:"Route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteUpdateByRoleIDAndPathReq) Reset()         { *m = RouteUpdateByRoleIDAndPathReq{} }
func (m *RouteUpdateByRoleIDAndPathReq) String() string { return proto.CompactTextString(m) }
func (*RouteUpdateByRoleIDAndPathReq) ProtoMessage()    {}
func (*RouteUpdateByRoleIDAndPathReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{13}
}

func (m *RouteUpdateByRoleIDAndPathReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteUpdateByRoleIDAndPathReq.Unmarshal(m, b)
}
func (m *RouteUpdateByRoleIDAndPathReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteUpdateByRoleIDAndPathReq.Marshal(b, m, deterministic)
}
func (m *RouteUpdateByRoleIDAndPathReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteUpdateByRoleIDAndPathReq.Merge(m, src)
}
func (m *RouteUpdateByRoleIDAndPathReq) XXX_Size() int {
	return xxx_messageInfo_RouteUpdateByRoleIDAndPathReq.Size(m)
}
func (m *RouteUpdateByRoleIDAndPathReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteUpdateByRoleIDAndPathReq.DiscardUnknown(m)
}

var xxx_messageInfo_RouteUpdateByRoleIDAndPathReq proto.InternalMessageInfo

func (m *RouteUpdateByRoleIDAndPathReq) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type RouteUpdateByRoleIDAndPathRes struct {
	// return number of Routes updated
	// should equal 1 on success
	Updated              *wrappers.Int64Value `protobuf:"bytes,1,opt,name=Updated,proto3" json:"Updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RouteUpdateByRoleIDAndPathRes) Reset()         { *m = RouteUpdateByRoleIDAndPathRes{} }
func (m *RouteUpdateByRoleIDAndPathRes) String() string { return proto.CompactTextString(m) }
func (*RouteUpdateByRoleIDAndPathRes) ProtoMessage()    {}
func (*RouteUpdateByRoleIDAndPathRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{14}
}

func (m *RouteUpdateByRoleIDAndPathRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteUpdateByRoleIDAndPathRes.Unmarshal(m, b)
}
func (m *RouteUpdateByRoleIDAndPathRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteUpdateByRoleIDAndPathRes.Marshal(b, m, deterministic)
}
func (m *RouteUpdateByRoleIDAndPathRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteUpdateByRoleIDAndPathRes.Merge(m, src)
}
func (m *RouteUpdateByRoleIDAndPathRes) XXX_Size() int {
	return xxx_messageInfo_RouteUpdateByRoleIDAndPathRes.Size(m)
}
func (m *RouteUpdateByRoleIDAndPathRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteUpdateByRoleIDAndPathRes.DiscardUnknown(m)
}

var xxx_messageInfo_RouteUpdateByRoleIDAndPathRes proto.InternalMessageInfo

func (m *RouteUpdateByRoleIDAndPathRes) GetUpdated() *wrappers.Int64Value {
	if m != nil {
		return m.Updated
	}
	return nil
}

type RouteDeleteReq struct {
	// delete a Route by id
	ID                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RouteDeleteReq) Reset()         { *m = RouteDeleteReq{} }
func (m *RouteDeleteReq) String() string { return proto.CompactTextString(m) }
func (*RouteDeleteReq) ProtoMessage()    {}
func (*RouteDeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{15}
}

func (m *RouteDeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteDeleteReq.Unmarshal(m, b)
}
func (m *RouteDeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteDeleteReq.Marshal(b, m, deterministic)
}
func (m *RouteDeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteDeleteReq.Merge(m, src)
}
func (m *RouteDeleteReq) XXX_Size() int {
	return xxx_messageInfo_RouteDeleteReq.Size(m)
}
func (m *RouteDeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteDeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_RouteDeleteReq proto.InternalMessageInfo

func (m *RouteDeleteReq) GetID() *wrappers.StringValue {
	if m != nil {
		return m.ID
	}
	return nil
}

type RouteDeleteRes struct {
	// return number of Routes deleted
	// should equal 1 on success
	Deleted              *wrappers.Int64Value `protobuf:"bytes,1,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RouteDeleteRes) Reset()         { *m = RouteDeleteRes{} }
func (m *RouteDeleteRes) String() string { return proto.CompactTextString(m) }
func (*RouteDeleteRes) ProtoMessage()    {}
func (*RouteDeleteRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{16}
}

func (m *RouteDeleteRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteDeleteRes.Unmarshal(m, b)
}
func (m *RouteDeleteRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteDeleteRes.Marshal(b, m, deterministic)
}
func (m *RouteDeleteRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteDeleteRes.Merge(m, src)
}
func (m *RouteDeleteRes) XXX_Size() int {
	return xxx_messageInfo_RouteDeleteRes.Size(m)
}
func (m *RouteDeleteRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteDeleteRes.DiscardUnknown(m)
}

var xxx_messageInfo_RouteDeleteRes proto.InternalMessageInfo

func (m *RouteDeleteRes) GetDeleted() *wrappers.Int64Value {
	if m != nil {
		return m.Deleted
	}
	return nil
}

func init() {
	proto.RegisterType((*Route)(nil), "api.Route")
	proto.RegisterType((*RouteListReq)(nil), "api.RouteListReq")
	proto.RegisterType((*RouteListRes)(nil), "api.RouteListRes")
	proto.RegisterType((*RouteListByRoleIDReq)(nil), "api.RouteListByRoleIDReq")
	proto.RegisterType((*RouteListByRoleIDRes)(nil), "api.RouteListByRoleIDRes")
	proto.RegisterType((*RouteCreateReq)(nil), "api.RouteCreateReq")
	proto.RegisterType((*RouteCreateRes)(nil), "api.RouteCreateRes")
	proto.RegisterType((*RouteReadReq)(nil), "api.RouteReadReq")
	proto.RegisterType((*RouteReadRes)(nil), "api.RouteReadRes")
	proto.RegisterType((*RouteReadByRoleIDAndPathReq)(nil), "api.RouteReadByRoleIDAndPathReq")
	proto.RegisterType((*RouteReadByRoleIDAndPathRes)(nil), "api.RouteReadByRoleIDAndPathRes")
	proto.RegisterType((*RouteUpdateReq)(nil), "api.RouteUpdateReq")
	proto.RegisterType((*RouteUpdateRes)(nil), "api.RouteUpdateRes")
	proto.RegisterType((*RouteUpdateByRoleIDAndPathReq)(nil), "api.RouteUpdateByRoleIDAndPathReq")
	proto.RegisterType((*RouteUpdateByRoleIDAndPathRes)(nil), "api.RouteUpdateByRoleIDAndPathRes")
	proto.RegisterType((*RouteDeleteReq)(nil), "api.RouteDeleteReq")
	proto.RegisterType((*RouteDeleteRes)(nil), "api.RouteDeleteRes")
}

func init() { proto.RegisterFile("route.proto", fileDescriptor_0984d49a362b6b9f) }

var fileDescriptor_0984d49a362b6b9f = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x6b, 0x13, 0x41,
	0x14, 0x25, 0x1f, 0x4d, 0xf5, 0xa6, 0x14, 0x9c, 0x2a, 0xac, 0x53, 0x3f, 0xc2, 0x3c, 0xf5, 0x41,
	0xb6, 0x65, 0xad, 0x22, 0xa1, 0x28, 0x89, 0x81, 0x12, 0xa8, 0x50, 0xb6, 0x5a, 0xf0, 0x49, 0xb6,
	0xee, 0x34, 0x0e, 0x24, 0x99, 0xed, 0xce, 0x44, 0xe9, 0x3f, 0xf0, 0xaf, 0xf9, 0xaf, 0x64, 0x3e,
	0x76, 0x33, 0x49, 0xb6, 0xcd, 0xa4, 0x6f, 0x99, 0x3b, 0xe7, 0xcc, 0x3d, 0x7b, 0xee, 0xb9, 0x81,
	0x76, 0xce, 0x67, 0x92, 0x86, 0x59, 0xce, 0x25, 0x47, 0x8d, 0x24, 0x63, 0xf8, 0xf5, 0x88, 0xf3,
	0xd1, 0x98, 0x1e, 0xea, 0xd2, 0xd5, 0xec, 0xfa, 0x50, 0xb2, 0x09, 0x15, 0x32, 0x99, 0x64, 0x06,
	0x85, 0x5f, 0x2d, 0x03, 0xfe, 0xe4, 0x49, 0x96, 0xd1, 0x5c, 0x98, 0x7b, 0xf2, 0xaf, 0x01, 0x5b,
	0xb1, 0x7a, 0x15, 0xbd, 0x81, 0xfa, 0x70, 0x10, 0xd4, 0x3a, 0xb5, 0x83, 0x76, 0xf4, 0x22, 0x34,
	0xb4, 0xb0, 0xa0, 0x85, 0x17, 0x32, 0x67, 0xd3, 0xd1, 0x65, 0x32, 0x9e, 0xd1, 0xb8, 0x3e, 0x1c,
	0xa0, 0x63, 0x68, 0xc5, 0x7c, 0x4c, 0x87, 0x83, 0xa0, 0xee, 0xc1, 0xb0, 0x58, 0x74, 0x04, 0xcd,
	0xf3, 0x44, 0xfe, 0x0a, 0x1a, 0x1e, 0x1c, 0x8d, 0x44, 0x5d, 0x80, 0x73, 0x9a, 0x4f, 0x98, 0x10,
	0x8c, 0x4f, 0x83, 0xa6, 0xe6, 0xe1, 0x15, 0x5e, 0x9f, 0xf3, 0xb1, 0x61, 0x39, 0x68, 0xd4, 0x85,
	0xc7, 0x9f, 0x73, 0x9a, 0x48, 0x9a, 0xf6, 0x6f, 0x83, 0x2d, 0x8f, 0x96, 0x73, 0x38, 0xfa, 0x50,
	0x72, 0x7b, 0x32, 0x68, 0xdd, 0xd1, 0xf6, 0x6b, 0x61, 0x76, 0x3c, 0x07, 0xa3, 0x13, 0x80, 0x2f,
	0x3c, 0x65, 0xd7, 0x4c, 0xb7, 0xdd, 0xf6, 0x68, 0xeb, 0xe0, 0xd5, 0xf7, 0x16, 0xa7, 0x9e, 0x0c,
	0x1e, 0xad, 0x6d, 0xec, 0xa0, 0xc9, 0x2e, 0xec, 0xe8, 0x51, 0x9e, 0x31, 0x21, 0x63, 0x7a, 0x43,
	0xa2, 0x85, 0xb3, 0x40, 0x44, 0xcd, 0x6c, 0x26, 0xa9, 0x08, 0x6a, 0x9d, 0xc6, 0x41, 0x3b, 0x82,
	0x30, 0xc9, 0x58, 0xa8, 0x4b, 0xb1, 0xbd, 0x21, 0x67, 0xf0, 0xb4, 0xe4, 0xf4, 0x6f, 0xcd, 0xd8,
	0x62, 0x7a, 0xe3, 0xcc, 0xbb, 0xe6, 0x3f, 0x6f, 0xd2, 0xad, 0x7c, 0xcd, 0x4f, 0x49, 0x04, 0xbb,
	0xfa, 0x97, 0x71, 0x56, 0x69, 0xe8, 0xd8, 0xa8, 0x5a, 0x09, 0x2e, 0xc9, 0x5c, 0x90, 0x8f, 0x4b,
	0x1c, 0xb1, 0x59, 0xaa, 0xc9, 0x89, 0x75, 0x2c, 0xa6, 0x49, 0xaa, 0x3a, 0x6e, 0xc6, 0x3e, 0x5a,
	0x60, 0x0b, 0x0f, 0xbd, 0x9f, 0x60, 0xbf, 0x64, 0x14, 0xfe, 0xf4, 0xa6, 0xa9, 0x4a, 0xbe, 0xdf,
	0x07, 0xdf, 0xfb, 0x80, 0x8f, 0x82, 0xc2, 0xe5, 0x6f, 0x59, 0xea, 0xed, 0xf2, 0xe9, 0x12, 0x47,
	0xa0, 0x77, 0xb0, 0x6d, 0x0e, 0xa9, 0x65, 0xed, 0xaf, 0x98, 0x35, 0x9c, 0xca, 0xf7, 0xc7, 0xc6,
	0xab, 0x02, 0x4b, 0x7a, 0xf0, 0xd2, 0x79, 0xe8, 0x41, 0x06, 0x5c, 0xde, 0xff, 0xc4, 0x83, 0xa5,
	0x15, 0x49, 0x1a, 0xd0, 0x31, 0x35, 0xbe, 0x6c, 0x96, 0x85, 0xd3, 0x25, 0xbe, 0x16, 0x62, 0x0e,
	0x7e, 0x42, 0x2c, 0x36, 0xfa, 0xdb, 0xb4, 0xa9, 0xba, 0xa0, 0xf9, 0x6f, 0xf6, 0x53, 0xfd, 0x4f,
	0x37, 0xd5, 0x3a, 0xa1, 0x27, 0x73, 0x33, 0xec, 0xc2, 0xe3, 0x95, 0x92, 0x40, 0x03, 0xd8, 0x71,
	0x97, 0x0f, 0x3d, 0x5f, 0x84, 0x38, 0x2b, 0x8e, 0xef, 0xbc, 0x12, 0x28, 0x82, 0x96, 0x59, 0x29,
	0xb4, 0x37, 0x07, 0x95, 0x8b, 0x89, 0x2b, 0x8a, 0x6a, 0xf3, 0x9a, 0x2a, 0x95, 0xae, 0x4e, 0xbb,
	0x56, 0x78, 0xa5, 0x24, 0xd0, 0x77, 0xd8, 0xab, 0xc8, 0x30, 0xea, 0x2c, 0x22, 0x57, 0x23, 0x82,
	0xd7, 0x21, 0xb4, 0x78, 0x33, 0x55, 0x57, 0x7c, 0x99, 0x77, 0x5c, 0x51, 0x14, 0xe8, 0x07, 0x3c,
	0xab, 0x4c, 0x14, 0x22, 0xcb, 0xe8, 0x0a, 0x49, 0xeb, 0x31, 0x5a, 0x94, 0x99, 0xb0, 0x2b, 0xaa,
	0x0c, 0x1b, 0xae, 0x28, 0x8a, 0xab, 0x96, 0x0e, 0xca, 0xdb, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x88, 0x71, 0x2f, 0x68, 0x07, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouteServiceClient is the client API for RouteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouteServiceClient interface {
	List(ctx context.Context, in *RouteListReq, opts ...grpc.CallOption) (*RouteListRes, error)
	ListByRoleID(ctx context.Context, in *RouteListByRoleIDReq, opts ...grpc.CallOption) (*RouteListByRoleIDRes, error)
	Create(ctx context.Context, in *RouteCreateReq, opts ...grpc.CallOption) (*RouteCreateRes, error)
	Read(ctx context.Context, in *RouteReadReq, opts ...grpc.CallOption) (*RouteReadRes, error)
	ReadByRoleIDAndPath(ctx context.Context, in *RouteReadByRoleIDAndPathReq, opts ...grpc.CallOption) (*RouteReadByRoleIDAndPathRes, error)
	Update(ctx context.Context, in *RouteUpdateReq, opts ...grpc.CallOption) (*RouteUpdateRes, error)
	UpdateByRoleIDAndPath(ctx context.Context, in *RouteUpdateByRoleIDAndPathReq, opts ...grpc.CallOption) (*RouteUpdateByRoleIDAndPathRes, error)
	Delete(ctx context.Context, in *RouteDeleteReq, opts ...grpc.CallOption) (*RouteDeleteRes, error)
}

type routeServiceClient struct {
	cc *grpc.ClientConn
}

func NewRouteServiceClient(cc *grpc.ClientConn) RouteServiceClient {
	return &routeServiceClient{cc}
}

func (c *routeServiceClient) List(ctx context.Context, in *RouteListReq, opts ...grpc.CallOption) (*RouteListRes, error) {
	out := new(RouteListRes)
	err := c.cc.Invoke(ctx, "/api.RouteService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) ListByRoleID(ctx context.Context, in *RouteListByRoleIDReq, opts ...grpc.CallOption) (*RouteListByRoleIDRes, error) {
	out := new(RouteListByRoleIDRes)
	err := c.cc.Invoke(ctx, "/api.RouteService/ListByRoleID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) Create(ctx context.Context, in *RouteCreateReq, opts ...grpc.CallOption) (*RouteCreateRes, error) {
	out := new(RouteCreateRes)
	err := c.cc.Invoke(ctx, "/api.RouteService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) Read(ctx context.Context, in *RouteReadReq, opts ...grpc.CallOption) (*RouteReadRes, error) {
	out := new(RouteReadRes)
	err := c.cc.Invoke(ctx, "/api.RouteService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) ReadByRoleIDAndPath(ctx context.Context, in *RouteReadByRoleIDAndPathReq, opts ...grpc.CallOption) (*RouteReadByRoleIDAndPathRes, error) {
	out := new(RouteReadByRoleIDAndPathRes)
	err := c.cc.Invoke(ctx, "/api.RouteService/ReadByRoleIDAndPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) Update(ctx context.Context, in *RouteUpdateReq, opts ...grpc.CallOption) (*RouteUpdateRes, error) {
	out := new(RouteUpdateRes)
	err := c.cc.Invoke(ctx, "/api.RouteService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) UpdateByRoleIDAndPath(ctx context.Context, in *RouteUpdateByRoleIDAndPathReq, opts ...grpc.CallOption) (*RouteUpdateByRoleIDAndPathRes, error) {
	out := new(RouteUpdateByRoleIDAndPathRes)
	err := c.cc.Invoke(ctx, "/api.RouteService/UpdateByRoleIDAndPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) Delete(ctx context.Context, in *RouteDeleteReq, opts ...grpc.CallOption) (*RouteDeleteRes, error) {
	out := new(RouteDeleteRes)
	err := c.cc.Invoke(ctx, "/api.RouteService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouteServiceServer is the server API for RouteService service.
type RouteServiceServer interface {
	List(context.Context, *RouteListReq) (*RouteListRes, error)
	ListByRoleID(context.Context, *RouteListByRoleIDReq) (*RouteListByRoleIDRes, error)
	Create(context.Context, *RouteCreateReq) (*RouteCreateRes, error)
	Read(context.Context, *RouteReadReq) (*RouteReadRes, error)
	ReadByRoleIDAndPath(context.Context, *RouteReadByRoleIDAndPathReq) (*RouteReadByRoleIDAndPathRes, error)
	Update(context.Context, *RouteUpdateReq) (*RouteUpdateRes, error)
	UpdateByRoleIDAndPath(context.Context, *RouteUpdateByRoleIDAndPathReq) (*RouteUpdateByRoleIDAndPathRes, error)
	Delete(context.Context, *RouteDeleteReq) (*RouteDeleteRes, error)
}

func RegisterRouteServiceServer(s *grpc.Server, srv RouteServiceServer) {
	s.RegisterService(&_RouteService_serviceDesc, srv)
}

func _RouteService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RouteService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).List(ctx, req.(*RouteListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_ListByRoleID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteListByRoleIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).ListByRoleID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RouteService/ListByRoleID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).ListByRoleID(ctx, req.(*RouteListByRoleIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RouteService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).Create(ctx, req.(*RouteCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RouteService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).Read(ctx, req.(*RouteReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_ReadByRoleIDAndPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteReadByRoleIDAndPathReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).ReadByRoleIDAndPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RouteService/ReadByRoleIDAndPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).ReadByRoleIDAndPath(ctx, req.(*RouteReadByRoleIDAndPathReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RouteService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).Update(ctx, req.(*RouteUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_UpdateByRoleIDAndPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteUpdateByRoleIDAndPathReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).UpdateByRoleIDAndPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RouteService/UpdateByRoleIDAndPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).UpdateByRoleIDAndPath(ctx, req.(*RouteUpdateByRoleIDAndPathReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RouteService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).Delete(ctx, req.(*RouteDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RouteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.RouteService",
	HandlerType: (*RouteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _RouteService_List_Handler,
		},
		{
			MethodName: "ListByRoleID",
			Handler:    _RouteService_ListByRoleID_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _RouteService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _RouteService_Read_Handler,
		},
		{
			MethodName: "ReadByRoleIDAndPath",
			Handler:    _RouteService_ReadByRoleIDAndPath_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _RouteService_Update_Handler,
		},
		{
			MethodName: "UpdateByRoleIDAndPath",
			Handler:    _RouteService_UpdateByRoleIDAndPath_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RouteService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "route.proto",
}
