// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Session struct {
	// @inject_tag: bson:"_id"
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty" bson:"_id"`
	// @inject_tag: bson:"username"
	Username string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty" bson:"username"`
	// @inject_tag: bson:"remoteaddr"
	RemoteAddr string `protobuf:"bytes,3,opt,name=RemoteAddr,proto3" json:"RemoteAddr,omitempty" bson:"remoteaddr"`
	// @inject_tag: bson:"host"
	Host string `protobuf:"bytes,4,opt,name=Host,proto3" json:"Host,omitempty" bson:"host"`
	// @inject_tag: bson:"createdat"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty" bson:"createdat"`
	// @inject_tag: bson:"expiresat"
	ExpiresAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=ExpiresAt,proto3" json:"ExpiresAt,omitempty" bson:"expiresat"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{0}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Session) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Session) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func (m *Session) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Session) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Session) GetExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

type SessionListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *SessionListReq) Reset()         { *m = SessionListReq{} }
func (m *SessionListReq) String() string { return proto.CompactTextString(m) }
func (*SessionListReq) ProtoMessage()    {}
func (*SessionListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{1}
}

func (m *SessionListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionListReq.Unmarshal(m, b)
}
func (m *SessionListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionListReq.Marshal(b, m, deterministic)
}
func (m *SessionListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionListReq.Merge(m, src)
}
func (m *SessionListReq) XXX_Size() int {
	return xxx_messageInfo_SessionListReq.Size(m)
}
func (m *SessionListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionListReq.DiscardUnknown(m)
}

var xxx_messageInfo_SessionListReq proto.InternalMessageInfo

type SessionListRes struct {
	// return a collection of Sessions
	Sessions             []*Session `protobuf:"bytes,1,rep,name=Sessions,proto3" json:"Sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-" bson:"-"`
	XXX_unrecognized     []byte     `json:"-" bson:"-"`
	XXX_sizecache        int32      `json:"-" bson:"-"`
}

func (m *SessionListRes) Reset()         { *m = SessionListRes{} }
func (m *SessionListRes) String() string { return proto.CompactTextString(m) }
func (*SessionListRes) ProtoMessage()    {}
func (*SessionListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{2}
}

func (m *SessionListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionListRes.Unmarshal(m, b)
}
func (m *SessionListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionListRes.Marshal(b, m, deterministic)
}
func (m *SessionListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionListRes.Merge(m, src)
}
func (m *SessionListRes) XXX_Size() int {
	return xxx_messageInfo_SessionListRes.Size(m)
}
func (m *SessionListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionListRes.DiscardUnknown(m)
}

var xxx_messageInfo_SessionListRes proto.InternalMessageInfo

func (m *SessionListRes) GetSessions() []*Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

func init() {
	proto.RegisterType((*Session)(nil), "api.Session")
	proto.RegisterType((*SessionListReq)(nil), "api.SessionListReq")
	proto.RegisterType((*SessionListRes)(nil), "api.SessionListRes")
}

func init() { proto.RegisterFile("session.proto", fileDescriptor_3a6be1b361fa6f14) }

var fileDescriptor_3a6be1b361fa6f14 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x14, 0x45, 0x49, 0x13, 0x6b, 0xfb, 0xaa, 0x45, 0x9e, 0x9b, 0x21, 0x0b, 0x0d, 0x59, 0x65, 0x35,
	0x95, 0xb8, 0x11, 0x77, 0xd1, 0x0a, 0x16, 0x5c, 0xa5, 0xfa, 0x01, 0xa9, 0x79, 0x96, 0x01, 0xd3,
	0x19, 0xe7, 0x8d, 0xe2, 0xcf, 0xfa, 0x2f, 0xd2, 0x49, 0x1a, 0x8b, 0x08, 0xee, 0x92, 0x73, 0xef,
	0x99, 0xb9, 0x03, 0xc7, 0x4c, 0xcc, 0x4a, 0x6f, 0xa4, 0xb1, 0xda, 0x69, 0x0c, 0x2b, 0xa3, 0xe2,
	0xf3, 0xb5, 0xd6, 0xeb, 0x57, 0x9a, 0x79, 0xb4, 0x7a, 0x7f, 0x99, 0x39, 0xd5, 0x10, 0xbb, 0xaa,
	0x31, 0x6d, 0x2b, 0xfd, 0x0a, 0xe0, 0x70, 0xd9, 0x7a, 0x38, 0x85, 0xc1, 0x62, 0x2e, 0x82, 0x24,
	0xc8, 0xc6, 0xe5, 0x60, 0x31, 0xc7, 0x18, 0x46, 0x4f, 0x4c, 0x76, 0x53, 0x35, 0x24, 0x06, 0x9e,
	0xf6, 0xff, 0x78, 0x06, 0x50, 0x52, 0xa3, 0x1d, 0x15, 0x75, 0x6d, 0x45, 0xe8, 0xd3, 0x3d, 0x82,
	0x08, 0xd1, 0xbd, 0x66, 0x27, 0x22, 0x9f, 0xf8, 0x6f, 0xbc, 0x82, 0xf1, 0xad, 0xa5, 0xca, 0x51,
	0x5d, 0x38, 0x71, 0x90, 0x04, 0xd9, 0x24, 0x8f, 0x65, 0x3b, 0x50, 0xee, 0x06, 0xca, 0xc7, 0xdd,
	0xc0, 0xf2, 0xa7, 0xbc, 0x35, 0xef, 0x3e, 0x8d, 0xb2, 0xc4, 0x85, 0x13, 0xc3, 0xff, 0xcd, 0xbe,
	0x9c, 0x9e, 0xc0, 0xb4, 0x7b, 0xde, 0x83, 0x62, 0x57, 0xd2, 0x5b, 0x7a, 0xfd, 0x8b, 0x30, 0x66,
	0x30, 0xea, 0x08, 0x8b, 0x20, 0x09, 0xb3, 0x49, 0x7e, 0x24, 0x2b, 0xa3, 0x64, 0x07, 0xcb, 0x3e,
	0xcd, 0x6f, 0x7a, 0x77, 0x49, 0xf6, 0x43, 0x3d, 0x13, 0x5e, 0x40, 0xb4, 0x3d, 0x06, 0x4f, 0xf7,
	0x8d, 0xee, 0xaa, 0xf8, 0x0f, 0xc8, 0xab, 0xa1, 0x1f, 0x7c, 0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0x15, 0xaf, 0x73, 0xcc, 0xaf, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SessionServiceClient is the client API for SessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SessionServiceClient interface {
	List(ctx context.Context, in *SessionListReq, opts ...grpc.CallOption) (*SessionListRes, error)
}

type sessionServiceClient struct {
	cc *grpc.ClientConn
}

func NewSessionServiceClient(cc *grpc.ClientConn) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) List(ctx context.Context, in *SessionListReq, opts ...grpc.CallOption) (*SessionListRes, error) {
	out := new(SessionListRes)
	err := c.cc.Invoke(ctx, "/api.SessionService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServiceServer is the server API for SessionService service.
type SessionServiceServer interface {
	List(context.Context, *SessionListReq) (*SessionListRes, error)
}

func RegisterSessionServiceServer(s *grpc.Server, srv SessionServiceServer) {
	s.RegisterService(&_SessionService_serviceDesc, srv)
}

func _SessionService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SessionService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).List(ctx, req.(*SessionListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _SessionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SessionService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session.proto",
}
