// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	// @inject_tag: bson:"_id"
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty" bson:"_id"`
	// @inject_tag: bson:"username"
	Username string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty" bson:"username"`
	// @inject_tag: bson:"groups"
	Groups []string `protobuf:"bytes,3,rep,name=Groups,proto3" json:"Groups,omitempty" bson:"groups"`
	// @inject_tag: bson:"createdby"
	CreatedBy string `protobuf:"bytes,4,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty" bson:"createdby"`
	// @inject_tag: bson:"createdat"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty" bson:"createdat"`
	// @inject_tag: bson:"modifiedby"
	ModifiedBy string `protobuf:"bytes,6,opt,name=ModifiedBy,proto3" json:"ModifiedBy,omitempty" bson:"modifiedby"`
	// @inject_tag: bson:"modifiedat"
	ModifiedAt           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=ModifiedAt,proto3" json:"ModifiedAt,omitempty" bson:"modifiedat"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *User) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetModifiedBy() string {
	if m != nil {
		return m.ModifiedBy
	}
	return ""
}

func (m *User) GetModifiedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedAt
	}
	return nil
}

type UserSliceReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSliceReq) Reset()         { *m = UserSliceReq{} }
func (m *UserSliceReq) String() string { return proto.CompactTextString(m) }
func (*UserSliceReq) ProtoMessage()    {}
func (*UserSliceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserSliceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSliceReq.Unmarshal(m, b)
}
func (m *UserSliceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSliceReq.Marshal(b, m, deterministic)
}
func (m *UserSliceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSliceReq.Merge(m, src)
}
func (m *UserSliceReq) XXX_Size() int {
	return xxx_messageInfo_UserSliceReq.Size(m)
}
func (m *UserSliceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSliceReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserSliceReq proto.InternalMessageInfo

type UserSliceRes struct {
	// return a collection of users
	Users                []*User  `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSliceRes) Reset()         { *m = UserSliceRes{} }
func (m *UserSliceRes) String() string { return proto.CompactTextString(m) }
func (*UserSliceRes) ProtoMessage()    {}
func (*UserSliceRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserSliceRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSliceRes.Unmarshal(m, b)
}
func (m *UserSliceRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSliceRes.Marshal(b, m, deterministic)
}
func (m *UserSliceRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSliceRes.Merge(m, src)
}
func (m *UserSliceRes) XXX_Size() int {
	return xxx_messageInfo_UserSliceRes.Size(m)
}
func (m *UserSliceRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSliceRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserSliceRes proto.InternalMessageInfo

func (m *UserSliceRes) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserCreateReq struct {
	// create a user
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateReq) Reset()         { *m = UserCreateReq{} }
func (m *UserCreateReq) String() string { return proto.CompactTextString(m) }
func (*UserCreateReq) ProtoMessage()    {}
func (*UserCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateReq.Unmarshal(m, b)
}
func (m *UserCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateReq.Marshal(b, m, deterministic)
}
func (m *UserCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateReq.Merge(m, src)
}
func (m *UserCreateReq) XXX_Size() int {
	return xxx_messageInfo_UserCreateReq.Size(m)
}
func (m *UserCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateReq proto.InternalMessageInfo

func (m *UserCreateReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserCreateRes struct {
	// reutrn an id
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateRes) Reset()         { *m = UserCreateRes{} }
func (m *UserCreateRes) String() string { return proto.CompactTextString(m) }
func (*UserCreateRes) ProtoMessage()    {}
func (*UserCreateRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserCreateRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateRes.Unmarshal(m, b)
}
func (m *UserCreateRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateRes.Marshal(b, m, deterministic)
}
func (m *UserCreateRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateRes.Merge(m, src)
}
func (m *UserCreateRes) XXX_Size() int {
	return xxx_messageInfo_UserCreateRes.Size(m)
}
func (m *UserCreateRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateRes proto.InternalMessageInfo

func (m *UserCreateRes) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UserReadReq struct {
	// read a user by id
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReadReq) Reset()         { *m = UserReadReq{} }
func (m *UserReadReq) String() string { return proto.CompactTextString(m) }
func (*UserReadReq) ProtoMessage()    {}
func (*UserReadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserReadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReadReq.Unmarshal(m, b)
}
func (m *UserReadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReadReq.Marshal(b, m, deterministic)
}
func (m *UserReadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReadReq.Merge(m, src)
}
func (m *UserReadReq) XXX_Size() int {
	return xxx_messageInfo_UserReadReq.Size(m)
}
func (m *UserReadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReadReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserReadReq proto.InternalMessageInfo

func (m *UserReadReq) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UserReadRes struct {
	// return a user
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReadRes) Reset()         { *m = UserReadRes{} }
func (m *UserReadRes) String() string { return proto.CompactTextString(m) }
func (*UserReadRes) ProtoMessage()    {}
func (*UserReadRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *UserReadRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReadRes.Unmarshal(m, b)
}
func (m *UserReadRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReadRes.Marshal(b, m, deterministic)
}
func (m *UserReadRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReadRes.Merge(m, src)
}
func (m *UserReadRes) XXX_Size() int {
	return xxx_messageInfo_UserReadRes.Size(m)
}
func (m *UserReadRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReadRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserReadRes proto.InternalMessageInfo

func (m *UserReadRes) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserByUsernameReq struct {
	// read a user by id
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserByUsernameReq) Reset()         { *m = UserByUsernameReq{} }
func (m *UserByUsernameReq) String() string { return proto.CompactTextString(m) }
func (*UserByUsernameReq) ProtoMessage()    {}
func (*UserByUsernameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *UserByUsernameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserByUsernameReq.Unmarshal(m, b)
}
func (m *UserByUsernameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserByUsernameReq.Marshal(b, m, deterministic)
}
func (m *UserByUsernameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserByUsernameReq.Merge(m, src)
}
func (m *UserByUsernameReq) XXX_Size() int {
	return xxx_messageInfo_UserByUsernameReq.Size(m)
}
func (m *UserByUsernameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserByUsernameReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserByUsernameReq proto.InternalMessageInfo

func (m *UserByUsernameReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserByUsernameRes struct {
	// return a user
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserByUsernameRes) Reset()         { *m = UserByUsernameRes{} }
func (m *UserByUsernameRes) String() string { return proto.CompactTextString(m) }
func (*UserByUsernameRes) ProtoMessage()    {}
func (*UserByUsernameRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *UserByUsernameRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserByUsernameRes.Unmarshal(m, b)
}
func (m *UserByUsernameRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserByUsernameRes.Marshal(b, m, deterministic)
}
func (m *UserByUsernameRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserByUsernameRes.Merge(m, src)
}
func (m *UserByUsernameRes) XXX_Size() int {
	return xxx_messageInfo_UserByUsernameRes.Size(m)
}
func (m *UserByUsernameRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserByUsernameRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserByUsernameRes proto.InternalMessageInfo

func (m *UserByUsernameRes) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserUpdateReq struct {
	// update a user by id
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdateReq) Reset()         { *m = UserUpdateReq{} }
func (m *UserUpdateReq) String() string { return proto.CompactTextString(m) }
func (*UserUpdateReq) ProtoMessage()    {}
func (*UserUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *UserUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateReq.Unmarshal(m, b)
}
func (m *UserUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateReq.Marshal(b, m, deterministic)
}
func (m *UserUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateReq.Merge(m, src)
}
func (m *UserUpdateReq) XXX_Size() int {
	return xxx_messageInfo_UserUpdateReq.Size(m)
}
func (m *UserUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateReq proto.InternalMessageInfo

func (m *UserUpdateReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserUpdateRes struct {
	// return number of users updated
	// should equal 1 on success
	Updated              int64    `protobuf:"varint,1,opt,name=Updated,proto3" json:"Updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdateRes) Reset()         { *m = UserUpdateRes{} }
func (m *UserUpdateRes) String() string { return proto.CompactTextString(m) }
func (*UserUpdateRes) ProtoMessage()    {}
func (*UserUpdateRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *UserUpdateRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateRes.Unmarshal(m, b)
}
func (m *UserUpdateRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateRes.Marshal(b, m, deterministic)
}
func (m *UserUpdateRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateRes.Merge(m, src)
}
func (m *UserUpdateRes) XXX_Size() int {
	return xxx_messageInfo_UserUpdateRes.Size(m)
}
func (m *UserUpdateRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateRes proto.InternalMessageInfo

func (m *UserUpdateRes) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type UserDeleteReq struct {
	// delete a user by id
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDeleteReq) Reset()         { *m = UserDeleteReq{} }
func (m *UserDeleteReq) String() string { return proto.CompactTextString(m) }
func (*UserDeleteReq) ProtoMessage()    {}
func (*UserDeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *UserDeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDeleteReq.Unmarshal(m, b)
}
func (m *UserDeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDeleteReq.Marshal(b, m, deterministic)
}
func (m *UserDeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDeleteReq.Merge(m, src)
}
func (m *UserDeleteReq) XXX_Size() int {
	return xxx_messageInfo_UserDeleteReq.Size(m)
}
func (m *UserDeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserDeleteReq proto.InternalMessageInfo

func (m *UserDeleteReq) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UserDeleteRes struct {
	// return number of users deleted
	// should equal 1 on success
	Deleted              int64    `protobuf:"varint,1,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDeleteRes) Reset()         { *m = UserDeleteRes{} }
func (m *UserDeleteRes) String() string { return proto.CompactTextString(m) }
func (*UserDeleteRes) ProtoMessage()    {}
func (*UserDeleteRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *UserDeleteRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDeleteRes.Unmarshal(m, b)
}
func (m *UserDeleteRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDeleteRes.Marshal(b, m, deterministic)
}
func (m *UserDeleteRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDeleteRes.Merge(m, src)
}
func (m *UserDeleteRes) XXX_Size() int {
	return xxx_messageInfo_UserDeleteRes.Size(m)
}
func (m *UserDeleteRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDeleteRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserDeleteRes proto.InternalMessageInfo

func (m *UserDeleteRes) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*UserSliceReq)(nil), "api.UserSliceReq")
	proto.RegisterType((*UserSliceRes)(nil), "api.UserSliceRes")
	proto.RegisterType((*UserCreateReq)(nil), "api.UserCreateReq")
	proto.RegisterType((*UserCreateRes)(nil), "api.UserCreateRes")
	proto.RegisterType((*UserReadReq)(nil), "api.UserReadReq")
	proto.RegisterType((*UserReadRes)(nil), "api.UserReadRes")
	proto.RegisterType((*UserByUsernameReq)(nil), "api.UserByUsernameReq")
	proto.RegisterType((*UserByUsernameRes)(nil), "api.UserByUsernameRes")
	proto.RegisterType((*UserUpdateReq)(nil), "api.UserUpdateReq")
	proto.RegisterType((*UserUpdateRes)(nil), "api.UserUpdateRes")
	proto.RegisterType((*UserDeleteReq)(nil), "api.UserDeleteReq")
	proto.RegisterType((*UserDeleteRes)(nil), "api.UserDeleteRes")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0x8f, 0xd2, 0x40,
	0x14, 0x4d, 0x5b, 0xe8, 0xda, 0x8b, 0x6e, 0xdc, 0xfb, 0xb0, 0x99, 0x4c, 0x5c, 0x69, 0xfa, 0xd4,
	0x35, 0xda, 0x9a, 0xfa, 0x62, 0x8c, 0x2f, 0x8b, 0x24, 0x86, 0x07, 0x5f, 0x8a, 0xfc, 0x80, 0x42,
	0x07, 0xd2, 0x04, 0x6c, 0xe9, 0x14, 0x13, 0xfe, 0x9b, 0xbf, 0xcd, 0x98, 0x99, 0xa1, 0xd3, 0x2f,
	0x13, 0xf6, 0x09, 0xce, 0xb9, 0xf7, 0x9e, 0x1e, 0xce, 0xa1, 0x00, 0x27, 0xce, 0xca, 0xa0, 0x28,
	0xf3, 0x2a, 0x47, 0x2b, 0x29, 0x32, 0x3a, 0xdd, 0xe5, 0xf9, 0x6e, 0xcf, 0x42, 0x49, 0xad, 0x4f,
	0xdb, 0xb0, 0xca, 0x0e, 0x8c, 0x57, 0xc9, 0xa1, 0x50, 0x5b, 0xde, 0x5f, 0x03, 0x46, 0x2b, 0xce,
	0x4a, 0xbc, 0x05, 0x73, 0x31, 0x27, 0x86, 0x6b, 0xf8, 0x4e, 0x6c, 0x2e, 0xe6, 0x48, 0xe1, 0x85,
	0xe0, 0x7f, 0x25, 0x07, 0x46, 0x4c, 0xc9, 0x6a, 0x8c, 0xf7, 0x60, 0x7f, 0x2f, 0xf3, 0x53, 0xc1,
	0x89, 0xe5, 0x5a, 0xbe, 0x13, 0x5f, 0x10, 0xbe, 0x01, 0xe7, 0x5b, 0xc9, 0x92, 0x8a, 0xa5, 0xb3,
	0x33, 0x19, 0xc9, 0xa3, 0x86, 0xc0, 0xcf, 0x7a, 0xfa, 0x54, 0x91, 0xb1, 0x6b, 0xf8, 0x93, 0x88,
	0x06, 0xca, 0x5f, 0x50, 0xfb, 0x0b, 0x7e, 0xd6, 0xfe, 0xe2, 0x66, 0x19, 0xdf, 0x02, 0xfc, 0xc8,
	0xd3, 0x6c, 0x9b, 0x49, 0x61, 0x5b, 0x0a, 0xb7, 0x18, 0xfc, 0xd2, 0xcc, 0x9f, 0x2a, 0x72, 0x73,
	0x55, 0xba, 0xb5, 0xed, 0xdd, 0xc2, 0x4b, 0xf1, 0xbb, 0x96, 0xfb, 0x6c, 0xc3, 0x62, 0x76, 0xf4,
	0xc2, 0x0e, 0xe6, 0x38, 0x85, 0xb1, 0xc0, 0x9c, 0x18, 0xae, 0xe5, 0x4f, 0x22, 0x27, 0x48, 0x8a,
	0x2c, 0x10, 0x4c, 0xac, 0x78, 0x2f, 0x80, 0x57, 0xe2, 0x8b, 0x72, 0x1b, 0xb3, 0x23, 0x3e, 0xa8,
	0x44, 0x65, 0x96, 0x9d, 0x03, 0x49, 0x7b, 0xd3, 0xee, 0x3e, 0xef, 0x27, 0xef, 0x3d, 0xc0, 0x44,
	0xae, 0xb3, 0x24, 0x15, 0x72, 0xfd, 0xf1, 0xfb, 0xf6, 0x98, 0x5f, 0x7b, 0x5a, 0x08, 0x77, 0xe2,
	0x73, 0x76, 0xae, 0xcb, 0x13, 0x92, 0xed, 0x6e, 0x8d, 0x6e, 0xb7, 0x5e, 0x34, 0x3c, 0xb8, 0xfa,
	0x90, 0x4b, 0x04, 0xab, 0x22, 0x7d, 0x5e, 0x04, 0x8f, 0xdd, 0x7d, 0x8e, 0x04, 0x6e, 0x14, 0x48,
	0xe5, 0x89, 0x15, 0xd7, 0xb0, 0x4e, 0x6b, 0xce, 0xf6, 0x4c, 0x49, 0xf7, 0xe3, 0x78, 0xec, 0x2e,
	0x48, 0x2d, 0x05, 0xb4, 0xd6, 0x05, 0x46, 0x7f, 0x4c, 0x15, 0xdd, 0x92, 0x95, 0xbf, 0xb3, 0x0d,
	0xc3, 0x0f, 0x30, 0x96, 0x35, 0xe3, 0x9d, 0x36, 0x58, 0xff, 0x0d, 0xe8, 0x80, 0xe2, 0xf8, 0x11,
	0x6c, 0x55, 0x1a, 0xa2, 0x1e, 0xea, 0xd6, 0xe9, 0x90, 0xe3, 0xf8, 0x0e, 0x46, 0xa2, 0x26, 0x7c,
	0xdd, 0x04, 0xa0, 0x4a, 0xa5, 0x7d, 0x86, 0xe3, 0x57, 0x80, 0x26, 0x73, 0xbc, 0xd7, 0xf3, 0x4e,
	0x73, 0xf4, 0xff, 0xbc, 0xf4, 0xa6, 0x12, 0x6b, 0x79, 0xd3, 0x75, 0xd0, 0x21, 0x27, 0x2f, 0x54,
	0x2e, 0xad, 0x0b, 0x9d, 0x32, 0x1d, 0x72, 0x7c, 0x6d, 0xcb, 0x37, 0xe9, 0xd3, 0xbf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x3a, 0xf6, 0xba, 0xaf, 0x65, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Slice(ctx context.Context, in *UserSliceReq, opts ...grpc.CallOption) (*UserSliceRes, error)
	Create(ctx context.Context, in *UserCreateReq, opts ...grpc.CallOption) (*UserCreateRes, error)
	Read(ctx context.Context, in *UserReadReq, opts ...grpc.CallOption) (*UserReadRes, error)
	ByUsername(ctx context.Context, in *UserByUsernameReq, opts ...grpc.CallOption) (*UserByUsernameRes, error)
	Update(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*UserUpdateRes, error)
	Delete(ctx context.Context, in *UserDeleteReq, opts ...grpc.CallOption) (*UserDeleteRes, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Slice(ctx context.Context, in *UserSliceReq, opts ...grpc.CallOption) (*UserSliceRes, error) {
	out := new(UserSliceRes)
	err := c.cc.Invoke(ctx, "/api.UserService/Slice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Create(ctx context.Context, in *UserCreateReq, opts ...grpc.CallOption) (*UserCreateRes, error) {
	out := new(UserCreateRes)
	err := c.cc.Invoke(ctx, "/api.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Read(ctx context.Context, in *UserReadReq, opts ...grpc.CallOption) (*UserReadRes, error) {
	out := new(UserReadRes)
	err := c.cc.Invoke(ctx, "/api.UserService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ByUsername(ctx context.Context, in *UserByUsernameReq, opts ...grpc.CallOption) (*UserByUsernameRes, error) {
	out := new(UserByUsernameRes)
	err := c.cc.Invoke(ctx, "/api.UserService/ByUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Update(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*UserUpdateRes, error) {
	out := new(UserUpdateRes)
	err := c.cc.Invoke(ctx, "/api.UserService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Delete(ctx context.Context, in *UserDeleteReq, opts ...grpc.CallOption) (*UserDeleteRes, error) {
	out := new(UserDeleteRes)
	err := c.cc.Invoke(ctx, "/api.UserService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Slice(context.Context, *UserSliceReq) (*UserSliceRes, error)
	Create(context.Context, *UserCreateReq) (*UserCreateRes, error)
	Read(context.Context, *UserReadReq) (*UserReadRes, error)
	ByUsername(context.Context, *UserByUsernameReq) (*UserByUsernameRes, error)
	Update(context.Context, *UserUpdateReq) (*UserUpdateRes, error)
	Delete(context.Context, *UserDeleteReq) (*UserDeleteRes, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Slice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSliceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Slice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/Slice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Slice(ctx, req.(*UserSliceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*UserCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Read(ctx, req.(*UserReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserByUsernameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/ByUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ByUsername(ctx, req.(*UserByUsernameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Update(ctx, req.(*UserUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Delete(ctx, req.(*UserDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Slice",
			Handler:    _UserService_Slice_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _UserService_Read_Handler,
		},
		{
			MethodName: "ByUsername",
			Handler:    _UserService_ByUsername_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
