// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string               `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Groups               []string             `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	CreatedBy            string               `protobuf:"bytes,4,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ModifiedBy           string               `protobuf:"bytes,6,opt,name=modifiedBy,proto3" json:"modifiedBy,omitempty"`
	ModifiedAt           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=modifiedAt,proto3" json:"modifiedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *User) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetModifiedBy() string {
	if m != nil {
		return m.ModifiedBy
	}
	return ""
}

func (m *User) GetModifiedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedAt
	}
	return nil
}

type UserSliceRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSliceRequest) Reset()         { *m = UserSliceRequest{} }
func (m *UserSliceRequest) String() string { return proto.CompactTextString(m) }
func (*UserSliceRequest) ProtoMessage()    {}
func (*UserSliceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserSliceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSliceRequest.Unmarshal(m, b)
}
func (m *UserSliceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSliceRequest.Marshal(b, m, deterministic)
}
func (m *UserSliceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSliceRequest.Merge(m, src)
}
func (m *UserSliceRequest) XXX_Size() int {
	return xxx_messageInfo_UserSliceRequest.Size(m)
}
func (m *UserSliceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSliceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserSliceRequest proto.InternalMessageInfo

type UserSliceResponse struct {
	// return a collection of users
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSliceResponse) Reset()         { *m = UserSliceResponse{} }
func (m *UserSliceResponse) String() string { return proto.CompactTextString(m) }
func (*UserSliceResponse) ProtoMessage()    {}
func (*UserSliceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserSliceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSliceResponse.Unmarshal(m, b)
}
func (m *UserSliceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSliceResponse.Marshal(b, m, deterministic)
}
func (m *UserSliceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSliceResponse.Merge(m, src)
}
func (m *UserSliceResponse) XXX_Size() int {
	return xxx_messageInfo_UserSliceResponse.Size(m)
}
func (m *UserSliceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSliceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserSliceResponse proto.InternalMessageInfo

func (m *UserSliceResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserCreateRequest struct {
	// create a user
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateRequest) Reset()         { *m = UserCreateRequest{} }
func (m *UserCreateRequest) String() string { return proto.CompactTextString(m) }
func (*UserCreateRequest) ProtoMessage()    {}
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateRequest.Unmarshal(m, b)
}
func (m *UserCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateRequest.Marshal(b, m, deterministic)
}
func (m *UserCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateRequest.Merge(m, src)
}
func (m *UserCreateRequest) XXX_Size() int {
	return xxx_messageInfo_UserCreateRequest.Size(m)
}
func (m *UserCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateRequest proto.InternalMessageInfo

func (m *UserCreateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserCreateResponse struct {
	// reutrn an id
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateResponse) Reset()         { *m = UserCreateResponse{} }
func (m *UserCreateResponse) String() string { return proto.CompactTextString(m) }
func (*UserCreateResponse) ProtoMessage()    {}
func (*UserCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateResponse.Unmarshal(m, b)
}
func (m *UserCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateResponse.Marshal(b, m, deterministic)
}
func (m *UserCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateResponse.Merge(m, src)
}
func (m *UserCreateResponse) XXX_Size() int {
	return xxx_messageInfo_UserCreateResponse.Size(m)
}
func (m *UserCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateResponse proto.InternalMessageInfo

func (m *UserCreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserReadRequest struct {
	// read a user by id
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReadRequest) Reset()         { *m = UserReadRequest{} }
func (m *UserReadRequest) String() string { return proto.CompactTextString(m) }
func (*UserReadRequest) ProtoMessage()    {}
func (*UserReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReadRequest.Unmarshal(m, b)
}
func (m *UserReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReadRequest.Marshal(b, m, deterministic)
}
func (m *UserReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReadRequest.Merge(m, src)
}
func (m *UserReadRequest) XXX_Size() int {
	return xxx_messageInfo_UserReadRequest.Size(m)
}
func (m *UserReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserReadRequest proto.InternalMessageInfo

func (m *UserReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserReadResponse struct {
	// return a user
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReadResponse) Reset()         { *m = UserReadResponse{} }
func (m *UserReadResponse) String() string { return proto.CompactTextString(m) }
func (*UserReadResponse) ProtoMessage()    {}
func (*UserReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *UserReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReadResponse.Unmarshal(m, b)
}
func (m *UserReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReadResponse.Marshal(b, m, deterministic)
}
func (m *UserReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReadResponse.Merge(m, src)
}
func (m *UserReadResponse) XXX_Size() int {
	return xxx_messageInfo_UserReadResponse.Size(m)
}
func (m *UserReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserReadResponse proto.InternalMessageInfo

func (m *UserReadResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserReadByUsernameResponse struct {
	// return a user
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReadByUsernameResponse) Reset()         { *m = UserReadByUsernameResponse{} }
func (m *UserReadByUsernameResponse) String() string { return proto.CompactTextString(m) }
func (*UserReadByUsernameResponse) ProtoMessage()    {}
func (*UserReadByUsernameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *UserReadByUsernameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReadByUsernameResponse.Unmarshal(m, b)
}
func (m *UserReadByUsernameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReadByUsernameResponse.Marshal(b, m, deterministic)
}
func (m *UserReadByUsernameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReadByUsernameResponse.Merge(m, src)
}
func (m *UserReadByUsernameResponse) XXX_Size() int {
	return xxx_messageInfo_UserReadByUsernameResponse.Size(m)
}
func (m *UserReadByUsernameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReadByUsernameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserReadByUsernameResponse proto.InternalMessageInfo

func (m *UserReadByUsernameResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserReadByUsernameRequest struct {
	// read a user by id
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReadByUsernameRequest) Reset()         { *m = UserReadByUsernameRequest{} }
func (m *UserReadByUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*UserReadByUsernameRequest) ProtoMessage()    {}
func (*UserReadByUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *UserReadByUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReadByUsernameRequest.Unmarshal(m, b)
}
func (m *UserReadByUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReadByUsernameRequest.Marshal(b, m, deterministic)
}
func (m *UserReadByUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReadByUsernameRequest.Merge(m, src)
}
func (m *UserReadByUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_UserReadByUsernameRequest.Size(m)
}
func (m *UserReadByUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReadByUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserReadByUsernameRequest proto.InternalMessageInfo

func (m *UserReadByUsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserUpdateRequest struct {
	// update a user by id
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdateRequest) Reset()         { *m = UserUpdateRequest{} }
func (m *UserUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UserUpdateRequest) ProtoMessage()    {}
func (*UserUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *UserUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateRequest.Unmarshal(m, b)
}
func (m *UserUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateRequest.Marshal(b, m, deterministic)
}
func (m *UserUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateRequest.Merge(m, src)
}
func (m *UserUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UserUpdateRequest.Size(m)
}
func (m *UserUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateRequest proto.InternalMessageInfo

func (m *UserUpdateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserUpdateResponse struct {
	// return number of users updated
	// should equal 1 on success
	Updated              int64    `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdateResponse) Reset()         { *m = UserUpdateResponse{} }
func (m *UserUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UserUpdateResponse) ProtoMessage()    {}
func (*UserUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *UserUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateResponse.Unmarshal(m, b)
}
func (m *UserUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateResponse.Marshal(b, m, deterministic)
}
func (m *UserUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateResponse.Merge(m, src)
}
func (m *UserUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UserUpdateResponse.Size(m)
}
func (m *UserUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateResponse proto.InternalMessageInfo

func (m *UserUpdateResponse) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type UserDeleteRequest struct {
	// delete a user by id
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDeleteRequest) Reset()         { *m = UserDeleteRequest{} }
func (m *UserDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*UserDeleteRequest) ProtoMessage()    {}
func (*UserDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *UserDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDeleteRequest.Unmarshal(m, b)
}
func (m *UserDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDeleteRequest.Marshal(b, m, deterministic)
}
func (m *UserDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDeleteRequest.Merge(m, src)
}
func (m *UserDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_UserDeleteRequest.Size(m)
}
func (m *UserDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserDeleteRequest proto.InternalMessageInfo

func (m *UserDeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserDeleteResponse struct {
	// return number of users deleted
	// should equal 1 on success
	Deleted              int64    `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDeleteResponse) Reset()         { *m = UserDeleteResponse{} }
func (m *UserDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*UserDeleteResponse) ProtoMessage()    {}
func (*UserDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *UserDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDeleteResponse.Unmarshal(m, b)
}
func (m *UserDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDeleteResponse.Marshal(b, m, deterministic)
}
func (m *UserDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDeleteResponse.Merge(m, src)
}
func (m *UserDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_UserDeleteResponse.Size(m)
}
func (m *UserDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserDeleteResponse proto.InternalMessageInfo

func (m *UserDeleteResponse) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*UserSliceRequest)(nil), "api.UserSliceRequest")
	proto.RegisterType((*UserSliceResponse)(nil), "api.UserSliceResponse")
	proto.RegisterType((*UserCreateRequest)(nil), "api.UserCreateRequest")
	proto.RegisterType((*UserCreateResponse)(nil), "api.UserCreateResponse")
	proto.RegisterType((*UserReadRequest)(nil), "api.UserReadRequest")
	proto.RegisterType((*UserReadResponse)(nil), "api.UserReadResponse")
	proto.RegisterType((*UserReadByUsernameResponse)(nil), "api.UserReadByUsernameResponse")
	proto.RegisterType((*UserReadByUsernameRequest)(nil), "api.UserReadByUsernameRequest")
	proto.RegisterType((*UserUpdateRequest)(nil), "api.UserUpdateRequest")
	proto.RegisterType((*UserUpdateResponse)(nil), "api.UserUpdateResponse")
	proto.RegisterType((*UserDeleteRequest)(nil), "api.UserDeleteRequest")
	proto.RegisterType((*UserDeleteResponse)(nil), "api.UserDeleteResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0x6f, 0xd3, 0x40,
	0x10, 0x94, 0xe3, 0xc4, 0x25, 0x1b, 0xa9, 0xc0, 0x8a, 0x16, 0x73, 0x82, 0x26, 0x18, 0x1e, 0xf2,
	0xe4, 0x8a, 0x14, 0x01, 0x85, 0xa7, 0x16, 0xfe, 0x00, 0x86, 0xfc, 0x00, 0x37, 0xde, 0x46, 0x27,
	0x25, 0xb5, 0xf1, 0xd9, 0x48, 0xfd, 0xf3, 0x15, 0xf2, 0x7d, 0xe4, 0xee, 0x5c, 0xaa, 0xe6, 0xd1,
	0x73, 0x3b, 0xb3, 0xbb, 0x33, 0x6b, 0x80, 0x56, 0x50, 0x9d, 0x56, 0x75, 0xd9, 0x94, 0x18, 0xe6,
	0x15, 0x67, 0xd3, 0x75, 0x59, 0xae, 0x37, 0x74, 0x2a, 0xa1, 0xab, 0xf6, 0xfa, 0xb4, 0xe1, 0x5b,
	0x12, 0x4d, 0xbe, 0xad, 0x54, 0x55, 0x72, 0x17, 0xc0, 0x70, 0x29, 0xa8, 0xc6, 0x43, 0x18, 0xf0,
	0x22, 0x0e, 0x66, 0xc1, 0x7c, 0x9c, 0x0d, 0x78, 0x81, 0x0c, 0x9e, 0x74, 0x62, 0x37, 0xf9, 0x96,
	0xe2, 0x81, 0x44, 0x77, 0xdf, 0x78, 0x0c, 0xd1, 0xba, 0x2e, 0xdb, 0x4a, 0xc4, 0xe1, 0x2c, 0x9c,
	0x8f, 0x33, 0xfd, 0x85, 0xaf, 0x61, 0xbc, 0xaa, 0x29, 0x6f, 0xa8, 0xb8, 0xbc, 0x8d, 0x87, 0x92,
	0x64, 0x01, 0xfc, 0xb2, 0x7b, 0xbd, 0x68, 0xe2, 0xd1, 0x2c, 0x98, 0x4f, 0x16, 0x2c, 0x55, 0xf3,
	0xa5, 0x66, 0xbe, 0xf4, 0xb7, 0x99, 0x2f, 0xb3, 0xc5, 0x78, 0x02, 0xb0, 0x2d, 0x0b, 0x7e, 0xcd,
	0xa5, 0x70, 0x24, 0x85, 0x1d, 0x04, 0xbf, 0xda, 0xf7, 0x8b, 0x26, 0x3e, 0x78, 0x54, 0xda, 0xa9,
	0x4e, 0x10, 0x9e, 0x75, 0xfb, 0xff, 0xda, 0xf0, 0x15, 0x65, 0xf4, 0xa7, 0x25, 0xd1, 0x24, 0x1f,
	0xe1, 0xb9, 0x83, 0x89, 0xaa, 0xbc, 0x11, 0x84, 0x53, 0x18, 0x75, 0x06, 0x88, 0x38, 0x98, 0x85,
	0xf3, 0xc9, 0x62, 0x9c, 0xe6, 0x15, 0x4f, 0xbb, 0xb2, 0x4c, 0xe1, 0xc9, 0x42, 0xb1, 0xbe, 0xcb,
	0xb1, 0xb5, 0x14, 0xbe, 0x81, 0x61, 0xf7, 0x2a, 0x8d, 0xf5, 0x48, 0x12, 0x4e, 0xde, 0x03, 0xba,
	0x1c, 0xdd, 0xaa, 0x97, 0x45, 0xf2, 0x16, 0x9e, 0x4a, 0x0e, 0xe5, 0x85, 0xd1, 0xed, 0x97, 0x7c,
	0x50, 0x6b, 0xa8, 0x12, 0x2d, 0xf3, 0x48, 0xef, 0x6f, 0xc0, 0x0c, 0xe5, 0xf2, 0x76, 0xa9, 0xb3,
	0xdd, 0x97, 0xfc, 0x19, 0x5e, 0xfd, 0x8f, 0xac, 0x86, 0x73, 0x6f, 0x27, 0xf0, 0x6f, 0xc7, 0xb8,
	0xb4, 0xac, 0x8a, 0xfd, 0x5d, 0x4a, 0x95, 0x4b, 0x86, 0xa3, 0x27, 0x8c, 0xe1, 0xa0, 0x95, 0x88,
	0xf2, 0x21, 0xcc, 0xcc, 0x67, 0xf2, 0x4e, 0xf5, 0xf8, 0x41, 0x1b, 0xb2, 0x3d, 0xfa, 0x8e, 0x69,
	0x51, 0x53, 0x64, 0x45, 0x0b, 0x89, 0xec, 0x44, 0xf5, 0xe7, 0xe2, 0x6e, 0x00, 0x13, 0x79, 0x15,
	0x54, 0xff, 0xe5, 0x2b, 0xc2, 0x4f, 0x30, 0x92, 0x07, 0x82, 0x47, 0xbb, 0x71, 0xdd, 0x23, 0x62,
	0xc7, 0x7d, 0x58, 0x77, 0x38, 0x87, 0x48, 0xc5, 0x8d, 0xb6, 0xc2, 0xbb, 0x19, 0xf6, 0xf2, 0x1e,
	0xae, 0xa9, 0x67, 0x30, 0xec, 0x0c, 0xc7, 0x17, 0xd6, 0x20, 0x7b, 0x12, 0xec, 0xa8, 0x87, 0x6a,
	0xd2, 0x4f, 0x38, 0xf4, 0x53, 0xc2, 0x13, 0xaf, 0xf0, 0x5e, 0x7c, 0x6c, 0xfa, 0xe0, 0xbb, 0x5d,
	0x41, 0x65, 0xe1, 0xac, 0xe0, 0x05, 0xea, 0xac, 0xd0, 0x0b, 0xed, 0x1c, 0x22, 0xe5, 0xb8, 0x43,
	0xf5, 0x72, 0x72, 0xa8, 0x7e, 0x34, 0x57, 0x91, 0xfc, 0x93, 0xcf, 0xfe, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x32, 0xd2, 0xb5, 0xcf, 0xe5, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Slice(ctx context.Context, in *UserSliceRequest, opts ...grpc.CallOption) (*UserSliceResponse, error)
	Create(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error)
	Read(ctx context.Context, in *UserReadRequest, opts ...grpc.CallOption) (*UserReadResponse, error)
	ReadByUsername(ctx context.Context, in *UserReadByUsernameRequest, opts ...grpc.CallOption) (*UserReadByUsernameResponse, error)
	Update(ctx context.Context, in *UserUpdateRequest, opts ...grpc.CallOption) (*UserUpdateResponse, error)
	Delete(ctx context.Context, in *UserDeleteRequest, opts ...grpc.CallOption) (*UserDeleteResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Slice(ctx context.Context, in *UserSliceRequest, opts ...grpc.CallOption) (*UserSliceResponse, error) {
	out := new(UserSliceResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/Slice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Create(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error) {
	out := new(UserCreateResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Read(ctx context.Context, in *UserReadRequest, opts ...grpc.CallOption) (*UserReadResponse, error) {
	out := new(UserReadResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ReadByUsername(ctx context.Context, in *UserReadByUsernameRequest, opts ...grpc.CallOption) (*UserReadByUsernameResponse, error) {
	out := new(UserReadByUsernameResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/ReadByUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Update(ctx context.Context, in *UserUpdateRequest, opts ...grpc.CallOption) (*UserUpdateResponse, error) {
	out := new(UserUpdateResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Delete(ctx context.Context, in *UserDeleteRequest, opts ...grpc.CallOption) (*UserDeleteResponse, error) {
	out := new(UserDeleteResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Slice(context.Context, *UserSliceRequest) (*UserSliceResponse, error)
	Create(context.Context, *UserCreateRequest) (*UserCreateResponse, error)
	Read(context.Context, *UserReadRequest) (*UserReadResponse, error)
	ReadByUsername(context.Context, *UserReadByUsernameRequest) (*UserReadByUsernameResponse, error)
	Update(context.Context, *UserUpdateRequest) (*UserUpdateResponse, error)
	Delete(context.Context, *UserDeleteRequest) (*UserDeleteResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Slice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSliceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Slice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/Slice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Slice(ctx, req.(*UserSliceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*UserCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Read(ctx, req.(*UserReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ReadByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReadByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ReadByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/ReadByUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ReadByUsername(ctx, req.(*UserReadByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Update(ctx, req.(*UserUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Delete(ctx, req.(*UserDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Slice",
			Handler:    _UserService_Slice_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _UserService_Read_Handler,
		},
		{
			MethodName: "ReadByUsername",
			Handler:    _UserService_ReadByUsername_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
